"use client"

import { useEffect, useState } from "react"
import Link from "next/link"
import { ArrowLeft, Tag } from "lucide-react"
import { useApp } from "@/contexts/app-context"
import { fetchWithRetry } from "@/lib/http/fetch-with-retry"
import { DashboardToolbar } from "@/components/studio/shared/dashboard-toolbar"
import { Card, CardContent } from "@/components/ui/card"
import { Skeleton } from "@/components/ui/skeleton"
import { ZipCodeMap } from "@/components/studio/operations/zip-code-map"

type Data = { totals: { orderCount: number; bookedSales: number; averageOrderValue: number; discountedOrderCount: number; discountAmount: number; discountRate: number }; rows: { studioId: number; zipCode: string; orderCount: number; bookedSales: number; averageOrderValue: number; revenueShare: number }[]; discountCodes: { studioId: number; code: string; description: string; orderCount: number; discountAmount: number; averageDiscount: number }[]; studios: { id: number; name: string; city: string; state: string; address: string | null; latitude: number | null; longitude: number | null }[] }
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" })

export function OrderGeographyDashboard() {
  const { selectedStudio, dateRange, studios } = useApp(); const [data, setData] = useState<Data | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true)
  const studioName = (studioId: number) => studios.find(studio => studio.id === studioId)?.studio_name ?? `Studio ${studioId}`
  useEffect(() => { const controller = new AbortController(); Promise.resolve().then(() => { if (!controller.signal.aborted) setLoading(true) }); fetchWithRetry(`/api/marketing/order-geography?${new URLSearchParams({ studioId: selectedStudio, startDate: dateRange.startDate, endDate: dateRange.endDate })}`, { signal: controller.signal }).then(async response => { const json = await response.json(); if (!response.ok) throw new Error(json.error); setData(json); setError(null) }).catch(fetchError => { if (fetchError.name !== "AbortError") setError(fetchError.message) }).finally(() => { if (!controller.signal.aborted) setLoading(false) }); return () => controller.abort() }, [selectedStudio, dateRange.startDate, dateRange.endDate])
  const zipGroups = data ? [...data.rows.reduce((groups, row) => { const rows = groups.get(row.studioId) ?? []; rows.push(row); groups.set(row.studioId, rows); return groups }, new Map<number, Data["rows"]>())].sort(([left], [right]) => studioName(left).localeCompare(studioName(right))) : []
  return <div className="space-y-6">
    <Link href="/marketing" className="inline-flex items-center gap-1 text-sm text-muted-foreground"><ArrowLeft className="size-4" />Marketing</Link>
    <DashboardToolbar title="Order geography & discounts" subtitle="Order value by billing ZIP, plus discount usage by promotion code." defaultPreset="custom" />
    {loading ? <Skeleton className="h-80" /> : error ? <Card><CardContent className="py-12 text-center">{error}</CardContent></Card> : data ? <>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Orders", data.totals.orderCount.toLocaleString(), `${data.totals.discountedOrderCount.toLocaleString()} discounted`], ["Booked sales", money.format(data.totals.bookedSales), `${data.totals.discountRate.toFixed(1)}% used a discount`], ["Average order", money.format(data.totals.averageOrderValue), "Per captured order"], ["Discounts", money.format(data.totals.discountAmount), "Item-level discounts"]].map(([label, value, detail]) => <Card key={label}><CardContent><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{detail}</p></CardContent></Card>)}</div>
      <ZipCodeMap rows={data.rows} studios={data.studios} />
      <Card><CardContent className="overflow-x-auto"><h2 className="mb-1 flex items-center gap-2 text-lg font-semibold"><Tag className="size-5" />Discount-code performance</h2><p className="mb-4 text-sm text-muted-foreground">Promotion usage separated by studio and discount code.</p><table className="w-full min-w-[780px] text-sm"><thead><tr className="border-b text-left"><th className="py-2">Studio</th><th>Code</th><th>Description</th><th className="text-right">Orders</th><th className="text-right">Total discount</th><th className="text-right">Avg. discount</th></tr></thead><tbody>{data.discountCodes.map(row => <tr className="border-b last:border-0" key={`${row.studioId}-${row.code}`}><td className="py-3">{studioName(row.studioId)}</td><td className="font-medium">{row.code}</td><td className="max-w-md text-muted-foreground">{row.description}</td><td className="text-right">{row.orderCount.toLocaleString()}</td><td className="text-right">{money.format(row.discountAmount)}</td><td className="text-right">{money.format(row.averageDiscount)}</td></tr>)}</tbody></table>{data.discountCodes.length === 0 ? <p className="py-12 text-center text-sm text-muted-foreground">No discounts were captured for this period.</p> : null}</CardContent></Card>
      <section className="space-y-4"><div><h2 className="text-lg font-semibold">ZIP-code performance</h2><p className="text-sm text-muted-foreground">Each ZIP&apos;s revenue share is calculated within its studio.</p></div>{zipGroups.length ? <div className="grid items-start gap-4 xl:grid-cols-2">{zipGroups.map(([studioId, rows]) => <Card key={studioId}><CardContent className="overflow-x-auto"><h3 className="mb-3 text-lg font-semibold">{studioName(studioId)}</h3><table className="w-full min-w-[600px] text-sm"><thead><tr className="border-b text-left"><th className="py-2">ZIP</th><th className="text-right">Orders</th><th className="text-right">Booked sales</th><th className="text-right">Avg. order</th><th className="text-right">Revenue share</th></tr></thead><tbody>{rows.map(row => <tr className="border-b last:border-0" key={row.zipCode}><td className="py-3 font-medium">{row.zipCode}</td><td className="text-right">{row.orderCount.toLocaleString()}</td><td className="text-right">{money.format(row.bookedSales)}</td><td className="text-right">{money.format(row.averageOrderValue)}</td><td className="text-right">{row.revenueShare.toFixed(1)}%</td></tr>)}</tbody></table></CardContent></Card>)}</div> : <Card><CardContent><p className="py-12 text-center text-sm text-muted-foreground">No enriched PTS orders are available for this period.</p></CardContent></Card>}</section>
    </> : null}
  </div>
}
