-- Versioned legal documents and an append-only acceptance ledger.

begin;

create table if not exists public.legal_documents (
  document_type text not null,
  version text not null,
  title text not null,
  effective_at timestamptz not null,
  content_sha256 text not null,
  is_current boolean not null default false,
  published_at timestamptz not null default now(),
  primary key (document_type, version),
  constraint legal_documents_type check (document_type in ('terms', 'privacy')),
  constraint legal_documents_hash check (content_sha256 ~ '^[0-9a-f]{64}$')
);

create unique index if not exists legal_documents_one_current_per_type
  on public.legal_documents (document_type)
  where is_current;

create table if not exists public.legal_acceptances (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete restrict,
  user_id uuid not null references auth.users(id) on delete restrict,
  terms_version text not null,
  terms_content_sha256 text not null,
  privacy_version text not null,
  privacy_content_sha256 text not null,
  acceptance_method text not null,
  accepted_at timestamptz not null default now(),
  ip_address inet,
  user_agent text,
  constraint legal_acceptances_method check (acceptance_method in ('onboarding', 'policy_update')),
  constraint legal_acceptances_terms_hash check (terms_content_sha256 ~ '^[0-9a-f]{64}$'),
  constraint legal_acceptances_privacy_hash check (privacy_content_sha256 ~ '^[0-9a-f]{64}$'),
  constraint legal_acceptances_versions_unique unique (organization_id, user_id, terms_version, privacy_version)
);

create index if not exists legal_acceptances_org_date_idx
  on public.legal_acceptances (organization_id, accepted_at desc);
create index if not exists legal_acceptances_user_date_idx
  on public.legal_acceptances (user_id, accepted_at desc);

create or replace function public.prevent_legal_acceptance_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  raise exception 'Legal acceptance records are append-only';
end;
$$;

drop trigger if exists legal_acceptances_append_only on public.legal_acceptances;
create trigger legal_acceptances_append_only
before update or delete on public.legal_acceptances
for each row execute function public.prevent_legal_acceptance_mutation();

alter table public.legal_documents enable row level security;
alter table public.legal_acceptances enable row level security;
revoke all on table public.legal_documents, public.legal_acceptances from public, anon, authenticated;
grant select, insert, update on table public.legal_documents to service_role;
grant select, insert on table public.legal_acceptances to service_role;
grant usage, select on sequence public.legal_acceptances_id_seq to service_role;

insert into public.legal_documents (document_type, version, title, effective_at, content_sha256, is_current)
values
  ('terms', '2026-08-11-draft', 'SASHA Terms of Service', '2026-08-11 00:00:00+00', '89232a4ec43842de15367e7ae7ac51503e6194f645060ebbdb52d55ebf2eb4f8', true),
  ('privacy', '2026-08-11-draft', 'SASHA Privacy Policy', '2026-08-11 00:00:00+00', 'f8a7e264f95beeb2e242533147696a43e274722a5374c9b6641f6c31e6e15d1f', true)
on conflict (document_type, version) do update set
  title = excluded.title,
  effective_at = excluded.effective_at,
  content_sha256 = excluded.content_sha256,
  is_current = excluded.is_current;

comment on table public.legal_acceptances is
  'Append-only evidence that an authenticated user accepted exact Terms and Privacy document versions. Never update or delete these rows.';

commit;
