-- Invite-only dashboard identity, tenant membership, studio access, and
-- integration-secret metadata. Secret values never belong in these tables.

begin;

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  onboarding_completed_at timestamptz,
  terms_version text,
  terms_accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_profiles_full_name_length
    check (full_name is null or char_length(full_name) between 2 and 120)
);

create table if not exists public.organization_memberships (
  organization_id bigint not null
    references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null,
  status text not null default 'active',
  invited_by uuid references auth.users(id) on delete set null,
  joined_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (organization_id, user_id),
  constraint organization_memberships_role
    check (role in ('owner', 'administrator', 'manager', 'viewer')),
  constraint organization_memberships_status
    check (status in ('invited', 'active', 'suspended'))
);

create table if not exists public.user_studio_access (
  organization_id bigint not null
    references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  studio_id bigint not null references public.studios(id) on delete cascade,
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (user_id, studio_id)
);

create table if not exists public.integration_secret_references (
  id bigint generated by default as identity primary key,
  organization_id bigint not null
    references public.organizations(id) on delete cascade,
  studio_id bigint references public.studios(id) on delete cascade,
  integration_type text not null,
  account_label text not null,
  secret_provider text not null,
  secret_reference text not null,
  connection_status text not null default 'pending',
  created_by uuid references auth.users(id) on delete set null,
  last_validated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, integration_type, secret_reference),
  constraint integration_secret_references_status
    check (connection_status in ('pending', 'valid', 'invalid', 'disabled')),
  constraint integration_secret_references_provider_length
    check (char_length(secret_provider) between 2 and 50),
  constraint integration_secret_references_reference_length
    check (char_length(secret_reference) between 3 and 500)
);

create index if not exists organization_memberships_user_status_idx
  on public.organization_memberships (user_id, status, organization_id);
create index if not exists user_studio_access_user_org_idx
  on public.user_studio_access (user_id, organization_id, studio_id);
create index if not exists integration_secret_references_org_studio_idx
  on public.integration_secret_references (organization_id, studio_id);

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.current_user_organization_ids()
returns setof bigint
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select membership.organization_id
  from public.organization_memberships membership
  where membership.user_id = (select auth.uid())
    and membership.status = 'active';
$$;

create or replace function private.current_user_studio_ids()
returns setof bigint
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select studio.id
  from public.studios studio
  join public.organization_memberships membership
    on membership.organization_id = studio.organization_id
   and membership.user_id = (select auth.uid())
   and membership.status = 'active'
  where studio.active = true
    and (
      membership.role in ('owner', 'administrator')
      or exists (
        select 1
        from public.user_studio_access access
        where access.user_id = membership.user_id
          and access.organization_id = membership.organization_id
          and access.studio_id = studio.id
      )
    );
$$;

revoke all on function private.current_user_organization_ids()
  from public, anon, authenticated;
revoke all on function private.current_user_studio_ids()
  from public, anon, authenticated;

alter table public.user_profiles enable row level security;
alter table public.organization_memberships enable row level security;
alter table public.user_studio_access enable row level security;
alter table public.integration_secret_references enable row level security;

revoke all on table public.user_profiles from anon, authenticated;
revoke all on table public.organization_memberships from anon, authenticated;
revoke all on table public.user_studio_access from anon, authenticated;
revoke all on table public.integration_secret_references from anon, authenticated;

grant select, insert, update, delete on table public.user_profiles to service_role;
grant select, insert, update, delete on table public.organization_memberships to service_role;
grant select, insert, update, delete on table public.user_studio_access to service_role;
grant select, insert, update, delete on table public.integration_secret_references to service_role;
grant usage, select on sequence public.integration_secret_references_id_seq
  to service_role;

comment on table public.organization_memberships is
  'Invite-only dashboard tenant membership. Authorization is enforced server-side and with RLS defense in depth.';
comment on table public.user_studio_access is
  'Explicit studio grants for manager and viewer roles. Owners and administrators inherit all active organization studios.';
comment on table public.integration_secret_references is
  'Non-secret integration metadata and references to an external encrypted secret store. Never store credentials or API tokens here.';

commit;
