begin;

create extension if not exists supabase_vault with schema vault;

create table public.homebase_integration_accounts (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  studio_id bigint not null references public.studios(id) on delete cascade,
  account_name text not null,
  location_uuid text,
  location_name text,
  secret_provider text not null default 'supabase_vault',
  secret_reference text not null,
  is_active boolean not null default true,
  last_validated_at timestamptz,
  last_collected_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, studio_id),
  unique (organization_id, location_uuid),
  constraint homebase_account_name_length check (char_length(trim(account_name)) between 2 and 120),
  constraint homebase_secret_provider check (secret_provider = 'supabase_vault')
);

create table public.homebase_labor_daily (
  organization_id bigint not null references public.organizations(id) on delete cascade,
  brand_id bigint not null references public.brands(id) on delete cascade,
  studio_id bigint not null references public.studios(id) on delete cascade,
  labor_date date not null,
  scheduled_hours numeric(12,4) not null default 0,
  actual_hours numeric(12,4) not null default 0,
  scheduled_cost numeric(14,2) not null default 0,
  actual_cost numeric(14,2) not null default 0,
  regular_hours numeric(12,4) not null default 0,
  overtime_hours numeric(12,4) not null default 0,
  double_overtime_hours numeric(12,4) not null default 0,
  retrieved_at timestamptz not null,
  updated_at timestamptz not null default now(),
  primary key (studio_id, labor_date)
);

create table public.homebase_shift_labor (
  organization_id bigint not null references public.organizations(id) on delete cascade,
  brand_id bigint not null references public.brands(id) on delete cascade,
  studio_id bigint not null references public.studios(id) on delete cascade,
  source_shift_id bigint not null,
  source_timecard_id bigint,
  role text,
  department text,
  scheduled_start timestamptz,
  scheduled_end timestamptz,
  clock_in timestamptz,
  clock_out timestamptz,
  scheduled_hours numeric(12,4) not null default 0,
  actual_hours numeric(12,4) not null default 0,
  scheduled_cost numeric(14,2) not null default 0,
  actual_cost numeric(14,2) not null default 0,
  note text,
  retrieved_at timestamptz not null,
  updated_at timestamptz not null default now(),
  primary key (studio_id, source_shift_id)
);

create or replace function public.create_homebase_connection_with_secret(
  p_organization_id bigint, p_account_name text, p_api_key text, p_studio_id bigint
) returns bigint language plpgsql security definer set search_path = public, vault, pg_temp as $$
declare account_id bigint; vault_secret_id uuid; target_brand_id bigint;
begin
  if char_length(trim(p_account_name)) not between 2 and 120 then raise exception 'Invalid Homebase account name'; end if;
  if char_length(trim(p_api_key)) not between 16 and 4096 then raise exception 'Invalid Homebase API key'; end if;
  select brand_id into target_brand_id from public.studios
    where id = p_studio_id and organization_id = p_organization_id and active = true;
  if target_brand_id is null then raise exception 'Studio not found'; end if;

  insert into public.homebase_integration_accounts
    (organization_id, studio_id, account_name, secret_reference)
  values (p_organization_id, p_studio_id, trim(p_account_name), 'pending:' || gen_random_uuid()::text)
  returning id into account_id;

  select vault.create_secret(jsonb_build_object('apiKey', trim(p_api_key))::text,
    'homebase-account-' || account_id::text,
    'Studio Intelligence Homebase read-only API key') into vault_secret_id;
  update public.homebase_integration_accounts set secret_reference = vault_secret_id::text where id = account_id;

  insert into public.studio_integrations
    (organization_id, brand_id, studio_id, integration_type, integration_name, external_id, is_active, configuration)
  values (p_organization_id, target_brand_id, p_studio_id, 'homebase', trim(p_account_name),
    'pending', true, jsonb_build_object('homebase_account_id', account_id));
  return account_id;
end; $$;

create or replace function public.get_homebase_account_secret(p_account_id bigint)
returns jsonb language plpgsql security definer set search_path = public, vault, pg_temp as $$
declare decrypted_value text;
begin
  select secret.decrypted_secret into decrypted_value
  from public.homebase_integration_accounts account
  join vault.decrypted_secrets secret on secret.id = account.secret_reference::uuid
  where account.id = p_account_id and account.is_active = true;
  if decrypted_value is null then raise exception 'Homebase account secret not found'; end if;
  return decrypted_value::jsonb;
end; $$;

create or replace function public.validate_homebase_connection(
  p_account_id bigint, p_location_uuid text, p_location_name text
) returns void language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if nullif(trim(p_location_uuid), '') is null then raise exception 'Invalid Homebase location'; end if;
  update public.homebase_integration_accounts
    set location_uuid = trim(p_location_uuid), location_name = nullif(trim(p_location_name), ''),
        last_validated_at = now(), updated_at = now()
    where id = p_account_id and is_active = true;
  update public.studio_integrations mapping
    set external_id = trim(p_location_uuid), updated_at = now()
    where mapping.integration_type = 'homebase' and mapping.is_active = true
      and mapping.configuration ->> 'homebase_account_id' = p_account_id::text;
end; $$;

create or replace view public.homebase_collection_targets as
select account.organization_id, account.id as account_id, studio.brand_id,
  studio.id as studio_id, studio.studio_code, studio.studio_name, studio.timezone,
  account.location_uuid, account.location_name
from public.homebase_integration_accounts account
join public.studios studio on studio.id = account.studio_id and studio.active = true
where account.is_active = true;

alter table public.homebase_integration_accounts enable row level security;
alter table public.homebase_labor_daily enable row level security;
alter table public.homebase_shift_labor enable row level security;
revoke all on table public.homebase_integration_accounts, public.homebase_labor_daily,
  public.homebase_shift_labor, public.homebase_collection_targets from public, anon, authenticated;
grant select, insert, update, delete on table public.homebase_integration_accounts,
  public.homebase_labor_daily, public.homebase_shift_labor to service_role;
grant select on table public.homebase_collection_targets to service_role;
grant usage, select on sequence public.homebase_integration_accounts_id_seq to service_role;
revoke all on function public.create_homebase_connection_with_secret(bigint,text,text,bigint),
  public.get_homebase_account_secret(bigint), public.validate_homebase_connection(bigint,text,text)
  from public, anon, authenticated;
grant execute on function public.create_homebase_connection_with_secret(bigint,text,text,bigint),
  public.get_homebase_account_secret(bigint), public.validate_homebase_connection(bigint,text,text)
  to service_role;

comment on table public.homebase_integration_accounts is 'One Vault-backed read-only Homebase API key per SASHA studio.';
comment on table public.homebase_shift_labor is 'Privacy-minimized shift labor facts without employee identity.';

commit;
