-- MNTN Connected TV daily warehouse facts and reporting metrics.
-- Attribution can mature for up to 30 days, so the producer should
-- re-upsert a rolling 35-day window on every daily run.

begin;

create table if not exists public.mntn_daily_metrics (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  brand_id bigint not null references public.brands(id) on delete cascade,
  studio_id bigint not null references public.studios(id) on delete cascade,
  advertiser_id text not null,
  advertiser_name text not null,
  report_date date not null,
  spend numeric(14, 2) not null default 0,
  impressions bigint not null default 0,
  households_reached bigint not null default 0,
  commercials_aired bigint not null default 0,
  verified_visits numeric(18, 4) not null default 0,
  conversions numeric(18, 4) not null default 0,
  order_value numeric(14, 2) not null default 0,
  roas numeric(14, 4) not null default 0,
  last_touch_visits numeric(18, 4) not null default 0,
  last_touch_conversions numeric(18, 4) not null default 0,
  last_touch_order_value numeric(14, 2) not null default 0,
  last_touch_roas numeric(14, 4) not null default 0,
  source_period_begin date,
  source_period_end date,
  retrieved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mntn_daily_metrics_natural_key
    unique (studio_id, advertiser_id, report_date),
  constraint mntn_daily_metrics_nonnegative check (
    spend >= 0
    and impressions >= 0
    and households_reached >= 0
    and commercials_aired >= 0
    and verified_visits >= 0
    and conversions >= 0
    and order_value >= 0
    and last_touch_visits >= 0
    and last_touch_conversions >= 0
    and last_touch_order_value >= 0
  )
);

create index if not exists mntn_daily_metrics_studio_date_idx
  on public.mntn_daily_metrics (studio_id, report_date desc);

create index if not exists mntn_daily_metrics_org_date_idx
  on public.mntn_daily_metrics (organization_id, report_date desc);

create index if not exists mntn_daily_metrics_advertiser_date_idx
  on public.mntn_daily_metrics (advertiser_id, report_date desc);

alter table public.mntn_daily_metrics enable row level security;

revoke all on table public.mntn_daily_metrics from anon, authenticated;
grant select, insert, update, delete on table public.mntn_daily_metrics to service_role;
grant usage, select on sequence public.mntn_daily_metrics_id_seq to service_role;

comment on table public.mntn_daily_metrics is
  'One MNTN Connected TV reporting row per studio, advertiser, and report date. Rolling-window upserts replace attribution metrics that mature over time.';
comment on column public.mntn_daily_metrics.verified_visits is
  'MNTN modeled verified visits; view-through attribution, not GA4 session attribution.';
comment on column public.mntn_daily_metrics.last_touch_visits is
  'MNTN visits where MNTN was the last measured advertising touch.';

create or replace view public.mntn_performance_daily
with (security_invoker = true)
as
select
  organization_id,
  brand_id,
  studio_id,
  advertiser_id,
  advertiser_name,
  report_date,
  spend,
  impressions,
  households_reached,
  commercials_aired,
  verified_visits,
  conversions,
  order_value,
  roas,
  last_touch_visits,
  last_touch_conversions,
  last_touch_order_value,
  last_touch_roas,
  case when impressions > 0 then spend / impressions * 1000 else 0 end as cpm,
  case when verified_visits > 0 then spend / verified_visits else 0 end
    as cost_per_verified_visit,
  case when conversions > 0 then spend / conversions else 0 end
    as cost_per_conversion,
  source_period_begin,
  source_period_end,
  retrieved_at
from public.mntn_daily_metrics;

revoke all on table public.mntn_performance_daily from anon, authenticated;
grant select on table public.mntn_performance_daily to service_role;

comment on view public.mntn_performance_daily is
  'Dashboard-ready MNTN daily delivery, modeled attribution, last-touch attribution, CPM, and acquisition-cost metrics.';

commit;
