-- Curated source directory for scalable, multi-studio marketing reporting.
-- Raw GA4 source/medium facts remain unchanged.

begin;

create table if not exists public.marketing_reporting_sources (
  id bigint generated by default as identity primary key,
  organization_id bigint references public.organizations(id) on delete cascade,
  brand_id bigint references public.brands(id) on delete cascade,
  studio_id bigint references public.studios(id) on delete cascade,
  source text not null,
  medium text not null,
  display_name text not null,
  vendor text not null,
  marketing_type text not null,
  traffic_category text not null,
  reporting_group text not null,
  visibility text not null default 'Featured'
    check (visibility in ('Featured', 'Grouped', 'Hidden')),
  group_label text,
  sort_order integer not null default 500,
  active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (studio_id is null or brand_id is not null)
    and (brand_id is null or organization_id is not null)
  ),
  check (visibility <> 'Grouped' or group_label is not null)
);

create unique index if not exists marketing_reporting_sources_scope_key
  on public.marketing_reporting_sources (
    coalesce(organization_id, 0),
    coalesce(brand_id, 0),
    coalesce(studio_id, 0),
    lower(source),
    lower(medium)
  );

create index if not exists marketing_reporting_sources_lookup_idx
  on public.marketing_reporting_sources (
    lower(source),
    lower(medium),
    active,
    organization_id,
    brand_id,
    studio_id
  );

alter table public.marketing_reporting_sources enable row level security;
revoke all on table public.marketing_reporting_sources from anon, authenticated;
grant select, insert, update, delete on table public.marketing_reporting_sources to service_role;
grant usage, select on sequence public.marketing_reporting_sources_id_seq to service_role;

insert into public.marketing_reporting_sources
  (
    source, medium, display_name, vendor, marketing_type, traffic_category,
    reporting_group, visibility, group_label, sort_order, notes
  )
values
  ('(direct)', '(none)', 'Direct', 'Direct', 'Direct', 'Direct',
    'Direct', 'Featured', null, 10, 'Always-visible direct traffic'),
  ('google', 'organic', 'Google Organic', 'Google', 'Organic', 'Organic Search',
    'Organic Search', 'Featured', null, 20, 'Always-visible Google organic traffic'),
  ('google', 'cpc', 'Google Paid', 'Google Ads', 'Paid', 'Paid Search',
    'Paid', 'Featured', null, 30, 'Always-visible Google paid traffic'),
  ('fb', 'paid', 'Meta Paid', 'Meta', 'Paid', 'Paid Social',
    'Paid', 'Featured', null, 40, 'Meta paid traffic'),
  ('ig', 'paid', 'Meta Paid', 'Meta', 'Paid', 'Paid Social',
    'Paid', 'Featured', null, 40, 'Meta paid traffic'),
  ('facebook.com', 'referral', 'Facebook Organic', 'Facebook', 'Organic', 'Organic Social',
    'Organic Social', 'Featured', null, 50, 'Facebook organic web traffic'),
  ('m.facebook.com', 'referral', 'Facebook Organic', 'Facebook', 'Organic', 'Organic Social',
    'Organic Social', 'Featured', null, 50, 'Facebook organic mobile traffic'),
  ('l.facebook.com', 'referral', 'Facebook Organic', 'Facebook', 'Organic', 'Organic Social',
    'Organic Social', 'Featured', null, 50, 'Facebook organic redirect traffic'),
  ('lm.facebook.com', 'referral', 'Facebook Organic', 'Facebook', 'Organic', 'Organic Social',
    'Organic Social', 'Featured', null, 50, 'Facebook organic mobile redirect traffic'),
  ('instagram.com', 'referral', 'Instagram Organic', 'Instagram', 'Organic', 'Organic Social',
    'Organic Social', 'Featured', null, 60, 'Instagram organic web traffic'),
  ('l.instagram.com', 'referral', 'Instagram Organic', 'Instagram', 'Organic', 'Organic Social',
    'Organic Social', 'Featured', null, 60, 'Instagram organic redirect traffic'),
  ('ig', 'social', 'Instagram Organic', 'Instagram', 'Organic', 'Organic Social',
    'Organic Social', 'Featured', null, 60, 'Instagram organic tagged traffic'),
  ('pinterest', 'organic', 'Pinterest Organic', 'Pinterest', 'Organic', 'Organic Social',
    'Organic Social', 'Featured', null, 70, 'Pinterest organic traffic'),
  ('linkedin.com', 'referral', 'LinkedIn Organic', 'LinkedIn', 'Organic', 'Organic Social',
    'Organic Social', 'Featured', null, 70, 'LinkedIn organic traffic'),
  ('eulerity', 'ads', 'Eulerity', 'Eulerity', 'Paid', 'Paid Multi-Channel',
    'Paid', 'Featured', null, 80, 'Eulerity remains separate from Meta'),
  ('mntn', 'television_prospecting', 'MNTN', 'MNTN', 'Paid', 'Connected TV',
    'Paid', 'Featured', null, 90, 'MNTN attribution; spend integration is not active'),
  ('experiencecolumbus.com', 'referral', 'Experience Columbus', 'Experience Columbus',
    'Partner', 'Tourism Referral', 'Tourism', 'Featured', null, 100,
    'Approved tourism partner'),
  ('columbus.simpleviewcrm.com', 'referral', 'Experience Columbus', 'Experience Columbus',
    'Partner', 'Tourism Referral', 'Tourism', 'Featured', null, 100,
    'Experience Columbus redirect'),
  ('shortnorth.org', 'referral', 'Short North Alliance', 'Short North Alliance',
    'Partner', 'Tourism Referral', 'Tourism', 'Featured', null, 110,
    'Approved local tourism partner'),
  ('gosoin.com', 'referral', 'SoIN Tourism', 'SoIN Tourism',
    'Partner', 'Tourism Referral', 'Tourism', 'Featured', null, 110,
    'Approved Southern Indiana tourism partner')
on conflict do nothing;

drop view public.ga4_source_medium_performance;

create view public.ga4_source_medium_performance
with (security_invoker = true)
as
select
  fact.organization_id,
  fact.brand_id,
  fact.studio_id,
  fact.attribution_date as report_date,
  fact.source,
  fact.medium,
  coalesce(directory.display_name, fallback.display_name) as display_name,
  coalesce(directory.vendor, mapping.vendor, fallback.vendor) as vendor,
  coalesce(directory.marketing_type, mapping.marketing_type, fallback.marketing_type) as marketing_type,
  coalesce(directory.traffic_category, mapping.traffic_category, fallback.traffic_category) as traffic_category,
  coalesce(directory.reporting_group, fallback.reporting_group) as reporting_group,
  coalesce(directory.visibility, fallback.visibility) as visibility,
  coalesce(directory.group_label, fallback.group_label) as group_label,
  coalesce(directory.sort_order, fallback.sort_order) as sort_order,
  fact.users as total_users,
  fact.new_users,
  fact.sessions,
  fact.engaged_sessions,
  fact.page_views,
  fact.engagement_rate,
  fact.average_session_duration,
  fact.key_events,
  fact.session_key_event_rate,
  fact.revenue as total_revenue
from public.marketing_attribution_daily fact
left join public.marketing_source_mapping mapping
  on mapping.active is true
 and lower(mapping.source) = lower(fact.source)
 and lower(mapping.medium) = lower(fact.medium)
left join lateral (
  select configured.*
  from public.marketing_reporting_sources configured
  where configured.active is true
    and lower(configured.source) = lower(fact.source)
    and lower(configured.medium) = lower(fact.medium)
    and (configured.organization_id is null or configured.organization_id = fact.organization_id)
    and (configured.brand_id is null or configured.brand_id = fact.brand_id)
    and (configured.studio_id is null or configured.studio_id = fact.studio_id)
  order by
    (configured.studio_id is not null) desc,
    (configured.brand_id is not null) desc,
    (configured.organization_id is not null) desc
  limit 1
) directory on true
cross join lateral (
  select
    case
      when lower(fact.medium) ~ '(^|_)(cpc|ppc|paid|paid_social|display|affiliate|cpv|cpm)($|_)'
        then coalesce(mapping.vendor, initcap(fact.source))
      when lower(fact.source) in ('facebook', 'facebook.com', 'm.facebook.com', 'l.facebook.com', 'lm.facebook.com')
        then 'Facebook Organic'
      when lower(fact.source) in ('instagram', 'instagram.com', 'l.instagram.com', 'ig')
        then 'Instagram Organic'
      else coalesce(mapping.description, mapping.vendor, initcap(fact.source))
    end as display_name,
    coalesce(mapping.vendor, initcap(fact.source), 'Unmapped') as vendor,
    case
      when lower(fact.medium) ~ '(^|_)(cpc|ppc|paid|paid_social|display|affiliate|cpv|cpm)($|_)'
        then 'Paid'
      when lower(fact.medium) in ('social', 'social-organic', 'organic_social')
        or lower(fact.source) ~ '(facebook|instagram|pinterest|linkedin|tiktok|youtube)'
        then 'Organic'
      when lower(fact.medium) = 'organic' then 'Organic'
      when lower(fact.medium) = 'referral' then 'Referral'
      else coalesce(mapping.marketing_type, 'Unmapped')
    end as marketing_type,
    case
      when lower(fact.medium) ~ '(^|_)(cpc|ppc|paid|paid_social|display|affiliate|cpv|cpm)($|_)'
        then coalesce(mapping.traffic_category, 'Paid')
      when lower(fact.medium) in ('social', 'social-organic', 'organic_social')
        or lower(fact.source) ~ '(facebook|instagram|pinterest|linkedin|tiktok|youtube)'
        then 'Organic Social'
      when lower(fact.medium) = 'organic' then 'Organic Search'
      when lower(fact.medium) = 'referral' then 'Referral'
      else coalesce(mapping.traffic_category, 'Unmapped')
    end as traffic_category,
    case
      when lower(fact.medium) ~ '(^|_)(cpc|ppc|paid|paid_social|display|affiliate|cpv|cpm)($|_)'
        then 'Paid'
      when lower(fact.medium) in ('social', 'social-organic', 'organic_social')
        or lower(fact.source) ~ '(facebook|instagram|pinterest|linkedin|tiktok|youtube)'
        then 'Organic Social'
      when lower(fact.source) = 'google' and lower(fact.medium) = 'organic'
        then 'Organic Search'
      when lower(fact.source) = '(direct)' and lower(fact.medium) = '(none)'
        then 'Direct'
      when lower(fact.medium) = 'referral' then 'Other Referrals'
      else 'Other Traffic'
    end as reporting_group,
    case
      when lower(fact.medium) ~ '(^|_)(cpc|ppc|paid|paid_social|display|affiliate|cpv|cpm)($|_)'
        or lower(fact.medium) in ('social', 'social-organic', 'organic_social')
        or lower(fact.source) ~ '(facebook|instagram|pinterest|linkedin|tiktok|youtube)'
        or (lower(fact.source) = 'google' and lower(fact.medium) = 'organic')
        or (lower(fact.source) = '(direct)' and lower(fact.medium) = '(none)')
        then 'Featured'
      when lower(fact.medium) = 'referral' then 'Grouped'
      else 'Hidden'
    end as visibility,
    case when lower(fact.medium) = 'referral' then 'Other Referrals' end as group_label,
    case
      when lower(fact.medium) ~ '(^|_)(cpc|ppc|paid|paid_social|display|affiliate|cpv|cpm)($|_)' then 200
      when lower(fact.medium) in ('social', 'social-organic', 'organic_social')
        or lower(fact.source) ~ '(facebook|instagram|pinterest|linkedin|tiktok|youtube)' then 300
      when lower(fact.medium) = 'referral' then 800
      else 900
    end as sort_order
) fallback;

revoke all on table public.ga4_source_medium_performance from anon, authenticated;
grant select on table public.ga4_source_medium_performance to service_role;

comment on table public.marketing_reporting_sources is
  'Curated global, organization, brand, and studio-level source directory for dashboard reporting.';
comment on view public.ga4_source_medium_performance is
  'GA4 source/medium facts enriched with scoped reporting labels and visibility; raw facts remain unchanged.';

commit;
