begin;

create table public.pts_third_party_class_credits (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  brand_id bigint not null references public.brands(id) on delete cascade,
  studio_id bigint not null references public.studios(id) on delete cascade,
  pts_location_id text not null,
  source_credit_key text not null,
  order_id text,
  external_booking_id text,
  order_date date,
  class_time timestamptz,
  painting text,
  original_amount numeric(14, 2) not null default 0,
  applied_amount numeric(14, 2) not null default 0,
  post_date date,
  raw_payload jsonb not null default '{}'::jsonb,
  retrieved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (studio_id, source_credit_key)
);

create index pts_third_party_credits_studio_class_idx
  on public.pts_third_party_class_credits (studio_id, class_time);
create index pts_third_party_credits_org_post_date_idx
  on public.pts_third_party_class_credits (organization_id, post_date desc);

alter table public.pts_third_party_class_credits enable row level security;
revoke all on table public.pts_third_party_class_credits from public, anon, authenticated;
grant select, insert, update, delete on table public.pts_third_party_class_credits to service_role;
grant usage, select on sequence public.pts_third_party_class_credits_id_seq to service_role;

create or replace view public.pts_third_party_class_credits_reporting
with (security_invoker = true)
as
select
  credit.*,
  case when matched.match_count = 1 then matched.id end as matched_class_id,
  case when matched.match_count = 1 then matched.source_event_key end as matched_source_event_key,
  case
    when credit.class_time is null then 'missing_class_time'
    when matched.match_count > 1 then 'ambiguous'
    when matched.id is null then 'unmatched'
    else 'matched'
  end as match_status
from public.pts_third_party_class_credits credit
left join lateral (
  select
    min(candidate.id) as id,
    min(candidate.source_event_key) as source_event_key,
    count(*) as match_count
  from public.pts_class_sales_daily candidate
  where candidate.organization_id = credit.organization_id
    and candidate.studio_id = credit.studio_id
    and candidate.class_time = credit.class_time
    and (
      credit.painting is null
      or lower(trim(candidate.painting)) = lower(trim(credit.painting))
    )
) matched on true;

create or replace view public.pts_class_sales_reporting
with (security_invoker = true)
as
with credit_totals as (
  select
    matched_class_id,
    sum(applied_amount) as third_party_sales
  from public.pts_third_party_class_credits_reporting
  where match_status = 'matched'
  group by matched_class_id
)
select
  class_sales.id,
  class_sales.organization_id,
  class_sales.brand_id,
  class_sales.studio_id,
  class_sales.pts_location_id,
  class_sales.report_date,
  class_sales.source_row_hash,
  class_sales.painting,
  class_sales.class_time,
  class_sales.room,
  class_sales.class_type,
  class_sales.seats_sold,
  class_sales.capacity,
  class_sales.percent_full,
  class_sales.lead_time_average,
  class_sales.class_sales + coalesce(credit_totals.third_party_sales, 0) as class_sales,
  class_sales.product_sales,
  class_sales.fee_sales,
  class_sales.net_sales + coalesce(credit_totals.third_party_sales, 0) as net_sales,
  class_sales.raw_payload,
  class_sales.retrieved_at,
  class_sales.created_at,
  class_sales.updated_at,
  class_sales.event_date,
  class_sales.source_event_key,
  class_sales.first_seen_at,
  class_sales.last_seen_at,
  class_sales.class_type as source_class_type,
  coalesce(mapping.reporting_class_type, 'Unmapped') as reporting_class_type,
  case when mapping.id is null then 'unmapped' else 'mapped' end as mapping_status,
  class_sales.class_sales as source_class_sales,
  class_sales.net_sales as source_net_sales,
  coalesce(credit_totals.third_party_sales, 0) as third_party_sales
from public.pts_class_sales_daily class_sales
left join credit_totals on credit_totals.matched_class_id = class_sales.id
left join public.pts_class_type_mappings mapping
  on mapping.organization_id = class_sales.organization_id
 and lower(trim(mapping.source_class_type)) = lower(trim(class_sales.class_type))
 and mapping.is_active;

create or replace view public.pts_daily_operations_reporting
with (security_invoker = true)
as
with class_totals as (
  select
    organization_id,
    brand_id,
    studio_id,
    event_date as report_date,
    count(*) as class_event_count,
    sum(seats_sold) as class_reported_seats_sold,
    sum(capacity) as class_reported_capacity,
    sum(class_sales) as class_reported_class_sales,
    sum(product_sales) as class_reported_product_sales,
    sum(fee_sales) as class_reported_fee_sales,
    sum(net_sales) as class_reported_net_sales,
    sum(third_party_sales) as third_party_class_sales
  from public.pts_class_sales_reporting
  group by organization_id, brand_id, studio_id, event_date
),
product_totals as (
  select
    organization_id,
    brand_id,
    studio_id,
    report_date,
    sum(net_sales) filter (where department = 'Food & Beverage') as food_and_beverage_sales,
    sum(net_sales) filter (where department = 'Other Products') as detailed_other_product_sales,
    sum(net_sales) filter (where mapping_status = 'unmapped') as unmapped_product_sales
  from public.pts_product_sales_reporting
  group by organization_id, brand_id, studio_id, report_date
)
select
  daily_summary.*,
  coalesce(class_totals.class_event_count, 0) as class_event_count,
  coalesce(class_totals.class_reported_seats_sold, 0) as class_reported_seats_sold,
  coalesce(class_totals.class_reported_capacity, 0) as class_reported_capacity,
  coalesce(class_totals.class_reported_class_sales, 0) as class_reported_class_sales,
  coalesce(class_totals.class_reported_product_sales, 0) as class_reported_product_sales,
  coalesce(class_totals.class_reported_fee_sales, 0) as class_reported_fee_sales,
  coalesce(class_totals.class_reported_net_sales, 0) as class_reported_net_sales,
  coalesce(product_totals.food_and_beverage_sales, 0) as food_and_beverage_sales,
  coalesce(product_totals.detailed_other_product_sales, 0) as detailed_other_product_sales,
  coalesce(product_totals.unmapped_product_sales, 0) as unmapped_product_sales,
  daily_summary.alcohol_sales + daily_summary.other_product_sales
    - coalesce(product_totals.food_and_beverage_sales, 0)
    - coalesce(product_totals.detailed_other_product_sales, 0)
    - coalesce(product_totals.unmapped_product_sales, 0)
    as product_reconciliation_difference,
  coalesce(class_totals.third_party_class_sales, 0) as third_party_class_sales
from public.pts_sales_daily_summary daily_summary
left join class_totals
  on class_totals.organization_id = daily_summary.organization_id
 and class_totals.brand_id = daily_summary.brand_id
 and class_totals.studio_id = daily_summary.studio_id
 and class_totals.report_date = daily_summary.report_date
left join product_totals
  on product_totals.organization_id = daily_summary.organization_id
 and product_totals.brand_id = daily_summary.brand_id
 and product_totals.studio_id = daily_summary.studio_id
 and product_totals.report_date = daily_summary.report_date;

revoke all on table public.pts_third_party_class_credits_reporting from public, anon, authenticated;
revoke all on table public.pts_class_sales_reporting from public, anon, authenticated;
revoke all on table public.pts_daily_operations_reporting from public, anon, authenticated;
grant select on table public.pts_third_party_class_credits_reporting to service_role;
grant select on table public.pts_class_sales_reporting to service_role;
grant select on table public.pts_daily_operations_reporting to service_role;

comment on table public.pts_third_party_class_credits is
  'Privacy-minimized PTS Third Party Class Credits. Customer names are intentionally excluded.';
comment on view public.pts_third_party_class_credits_reporting is
  'Third-party credits matched to completed classes by tenant, studio, class time, and painting.';

commit;
