begin;

create table if not exists public.pts_class_type_mappings (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  source_class_type text not null,
  reporting_class_type text not null check (
    reporting_class_type in (
      'Regular',
      'Little Brushes',
      'Paint it Forward',
      'Private Party',
      'Mobile Events',
      'No Class'
    )
  ),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, source_class_type)
);

create table if not exists public.pts_product_reporting_mappings (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  source_field text not null check (
    source_field in ('category', 'subcategory', 'item_name')
  ),
  source_value text not null,
  product_group text not null check (
    product_group in (
      'Liquor',
      'Wine',
      'Beer',
      'Misc Drinks',
      'Alcohol Specials',
      'Food',
      'Art Supplies',
      'Recorded Videos',
      'Frames',
      'Take Home Paint Kits',
      'Candles',
      'Misc'
    )
  ),
  department text not null check (
    department in ('Food & Beverage', 'Other Products')
  ),
  priority integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, source_field, source_value)
);

create index if not exists pts_class_type_mappings_lookup_idx
  on public.pts_class_type_mappings (
    organization_id,
    lower(source_class_type)
  )
  where is_active;

create index if not exists pts_product_reporting_mappings_lookup_idx
  on public.pts_product_reporting_mappings (
    organization_id,
    source_field,
    lower(source_value),
    priority
  )
  where is_active;

alter table public.pts_class_type_mappings enable row level security;
alter table public.pts_product_reporting_mappings enable row level security;

revoke all on table public.pts_class_type_mappings from anon, authenticated;
revoke all on table public.pts_product_reporting_mappings from anon, authenticated;

grant select, insert, update, delete
  on table public.pts_class_type_mappings to service_role;
grant select, insert, update, delete
  on table public.pts_product_reporting_mappings to service_role;

grant usage, select
  on sequence public.pts_class_type_mappings_id_seq to service_role;
grant usage, select
  on sequence public.pts_product_reporting_mappings_id_seq to service_role;

insert into public.pts_class_type_mappings (
  organization_id,
  source_class_type,
  reporting_class_type
)
select organization_id, source_class_type, reporting_class_type
from (
  values
    (1::bigint, 'Regular'::text, 'Regular'::text),
    (1::bigint, 'Holiday'::text, 'Regular'::text),
    (1::bigint, 'Little Brushes'::text, 'Little Brushes'::text),
    (1::bigint, 'Little Brushes in Studio'::text, 'Little Brushes'::text),
    (1::bigint, 'Painting it Forward'::text, 'Paint it Forward'::text),
    (1::bigint, 'Paint it Forward'::text, 'Paint it Forward'::text),
    (1::bigint, 'Private Party'::text, 'Private Party'::text),
    (1::bigint, 'Mobile'::text, 'Mobile Events'::text),
    (1::bigint, 'Mobile Party'::text, 'Mobile Events'::text)
) as mapping(organization_id, source_class_type, reporting_class_type)
where exists (
  select 1
  from public.organizations
  where id = mapping.organization_id
)
on conflict (organization_id, source_class_type)
do update set
  reporting_class_type = excluded.reporting_class_type,
  is_active = true,
  updated_at = now();

insert into public.pts_product_reporting_mappings (
  organization_id,
  source_field,
  source_value,
  product_group,
  department,
  priority
)
select
  organization_id,
  source_field,
  source_value,
  product_group,
  department,
  priority
from (
  values
    (1::bigint, 'category'::text, 'Liquor'::text, 'Liquor'::text, 'Food & Beverage'::text, 100),
    (1::bigint, 'subcategory'::text, 'Liquor'::text, 'Liquor'::text, 'Food & Beverage'::text, 50),
    (1::bigint, 'category'::text, 'Wine'::text, 'Wine'::text, 'Food & Beverage'::text, 100),
    (1::bigint, 'subcategory'::text, 'Wine'::text, 'Wine'::text, 'Food & Beverage'::text, 50),
    (1::bigint, 'category'::text, 'Beer'::text, 'Beer'::text, 'Food & Beverage'::text, 100),
    (1::bigint, 'subcategory'::text, 'Beer'::text, 'Beer'::text, 'Food & Beverage'::text, 50),
    (1::bigint, 'category'::text, 'Misc Drinks'::text, 'Misc Drinks'::text, 'Food & Beverage'::text, 100),
    (1::bigint, 'subcategory'::text, 'Misc Drinks'::text, 'Misc Drinks'::text, 'Food & Beverage'::text, 50),
    (1::bigint, 'category'::text, 'Alch Specials'::text, 'Alcohol Specials'::text, 'Food & Beverage'::text, 100),
    (1::bigint, 'category'::text, 'Alc Specials'::text, 'Alcohol Specials'::text, 'Food & Beverage'::text, 100),
    (1::bigint, 'subcategory'::text, 'Alch Specials'::text, 'Alcohol Specials'::text, 'Food & Beverage'::text, 50),
    (1::bigint, 'subcategory'::text, 'Alc Specials'::text, 'Alcohol Specials'::text, 'Food & Beverage'::text, 50),
    (1::bigint, 'category'::text, 'Food'::text, 'Food'::text, 'Food & Beverage'::text, 100),
    (1::bigint, 'subcategory'::text, 'Food'::text, 'Food'::text, 'Food & Beverage'::text, 50),
    (1::bigint, 'category'::text, 'Art Supplies'::text, 'Art Supplies'::text, 'Other Products'::text, 100),
    (1::bigint, 'subcategory'::text, 'Art Supplies'::text, 'Art Supplies'::text, 'Other Products'::text, 50),
    (1::bigint, 'category'::text, 'Recorded Videos'::text, 'Recorded Videos'::text, 'Other Products'::text, 100),
    (1::bigint, 'subcategory'::text, 'Recorded Videos'::text, 'Recorded Videos'::text, 'Other Products'::text, 50),
    (1::bigint, 'category'::text, 'Frames'::text, 'Frames'::text, 'Other Products'::text, 100),
    (1::bigint, 'subcategory'::text, 'Frames'::text, 'Frames'::text, 'Other Products'::text, 50),
    (1::bigint, 'category'::text, 'Take Home Paint Kits'::text, 'Take Home Paint Kits'::text, 'Other Products'::text, 100),
    (1::bigint, 'subcategory'::text, 'Take Home Paint Kits'::text, 'Take Home Paint Kits'::text, 'Other Products'::text, 50),
    (1::bigint, 'category'::text, 'Candles'::text, 'Candles'::text, 'Other Products'::text, 100),
    (1::bigint, 'subcategory'::text, 'Candles'::text, 'Candles'::text, 'Other Products'::text, 50),
    (1::bigint, 'category'::text, 'Misc'::text, 'Misc'::text, 'Other Products'::text, 100),
    (1::bigint, 'subcategory'::text, 'Misc'::text, 'Misc'::text, 'Other Products'::text, 50)
) as mapping(
  organization_id,
  source_field,
  source_value,
  product_group,
  department,
  priority
)
where exists (
  select 1
  from public.organizations
  where id = mapping.organization_id
)
on conflict (organization_id, source_field, source_value)
do update set
  product_group = excluded.product_group,
  department = excluded.department,
  priority = excluded.priority,
  is_active = true,
  updated_at = now();

create or replace view public.pts_class_sales_reporting
with (security_invoker = true)
as
select
  class_sales.*,
  class_sales.class_type as source_class_type,
  coalesce(mapping.reporting_class_type, 'Unmapped') as reporting_class_type,
  case when mapping.id is null then 'unmapped' else 'mapped' end as mapping_status
from public.pts_class_sales_daily class_sales
left join public.pts_class_type_mappings mapping
  on mapping.organization_id = class_sales.organization_id
 and lower(trim(mapping.source_class_type)) =
     lower(trim(class_sales.class_type))
 and mapping.is_active;

create or replace view public.pts_product_sales_reporting
with (security_invoker = true)
as
select
  product_sales.*,
  mapping.product_group,
  mapping.department,
  case when mapping.id is null then 'unmapped' else 'mapped' end as mapping_status,
  'No Class'::text as reporting_class_type
from public.pts_non_class_sales_items product_sales
left join lateral (
  select candidate.*
  from public.pts_product_reporting_mappings candidate
  where candidate.organization_id = product_sales.organization_id
    and candidate.is_active
    and lower(trim(candidate.source_value)) = lower(trim(
      case candidate.source_field
        when 'category' then product_sales.category
        when 'subcategory' then product_sales.subcategory
        when 'item_name' then product_sales.item_name
      end
    ))
  order by candidate.priority, candidate.id
  limit 1
) mapping on true;

create or replace view public.pts_daily_operations_reporting
with (security_invoker = true)
as
with class_totals as (
  select
    organization_id,
    brand_id,
    studio_id,
    event_date as report_date,
    count(*) as class_event_count,
    sum(seats_sold) as class_reported_seats_sold,
    sum(capacity) as class_reported_capacity,
    sum(class_sales) as class_reported_class_sales,
    sum(product_sales) as class_reported_product_sales,
    sum(fee_sales) as class_reported_fee_sales,
    sum(net_sales) as class_reported_net_sales
  from public.pts_class_sales_daily
  group by organization_id, brand_id, studio_id, event_date
),
product_totals as (
  select
    organization_id,
    brand_id,
    studio_id,
    report_date,
    sum(net_sales) filter (
      where department = 'Food & Beverage'
    ) as food_and_beverage_sales,
    sum(net_sales) filter (
      where department = 'Other Products'
    ) as detailed_other_product_sales,
    sum(net_sales) filter (
      where mapping_status = 'unmapped'
    ) as unmapped_product_sales
  from public.pts_product_sales_reporting
  group by organization_id, brand_id, studio_id, report_date
)
select
  daily_summary.*,
  coalesce(class_totals.class_event_count, 0) as class_event_count,
  coalesce(class_totals.class_reported_seats_sold, 0) as class_reported_seats_sold,
  coalesce(class_totals.class_reported_capacity, 0) as class_reported_capacity,
  coalesce(class_totals.class_reported_class_sales, 0) as class_reported_class_sales,
  coalesce(class_totals.class_reported_product_sales, 0) as class_reported_product_sales,
  coalesce(class_totals.class_reported_fee_sales, 0) as class_reported_fee_sales,
  coalesce(class_totals.class_reported_net_sales, 0) as class_reported_net_sales,
  coalesce(product_totals.food_and_beverage_sales, 0) as food_and_beverage_sales,
  coalesce(product_totals.detailed_other_product_sales, 0) as detailed_other_product_sales,
  coalesce(product_totals.unmapped_product_sales, 0) as unmapped_product_sales,
  daily_summary.alcohol_sales + daily_summary.other_product_sales
    - coalesce(product_totals.food_and_beverage_sales, 0)
    - coalesce(product_totals.detailed_other_product_sales, 0)
    - coalesce(product_totals.unmapped_product_sales, 0)
    as product_reconciliation_difference
from public.pts_sales_daily_summary daily_summary
left join class_totals
  on class_totals.organization_id = daily_summary.organization_id
 and class_totals.brand_id = daily_summary.brand_id
 and class_totals.studio_id = daily_summary.studio_id
 and class_totals.report_date = daily_summary.report_date
left join product_totals
  on product_totals.organization_id = daily_summary.organization_id
 and product_totals.brand_id = daily_summary.brand_id
 and product_totals.studio_id = daily_summary.studio_id
 and product_totals.report_date = daily_summary.report_date;

revoke all on table public.pts_class_sales_reporting from anon, authenticated;
revoke all on table public.pts_product_sales_reporting from anon, authenticated;
revoke all on table public.pts_daily_operations_reporting from anon, authenticated;

grant select on table public.pts_class_sales_reporting to service_role;
grant select on table public.pts_product_sales_reporting to service_role;
grant select on table public.pts_daily_operations_reporting to service_role;

comment on table public.pts_class_type_mappings is
  'Organization-governed mapping from raw PTS class Type values to operations reporting groups.';
comment on table public.pts_product_reporting_mappings is
  'Organization-governed mapping from PTS product category, subcategory, or item values to product groups and departments.';
comment on view public.pts_product_sales_reporting is
  'Product Sales lines with governed reporting groups. No Class denotes that the Product Sales source does not expose a stable class association.';

commit;
