begin;

create table if not exists public.pts_reservation_bookings (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  brand_id bigint not null references public.brands(id) on delete cascade,
  studio_id bigint not null references public.studios(id) on delete cascade,
  pts_location_id text not null,
  order_date date not null,
  source_row_key text not null,
  order_id text,
  confirmation text,
  order_datetime_text text,
  event_date date,
  class_label text,
  active_reservations numeric(12, 4) not null default 0,
  refunded_reservations numeric(12, 4) not null default 0,
  on_hold_reservations numeric(12, 4) not null default 0,
  checked_in_reservations numeric(12, 4) not null default 0,
  ordered_seats numeric(12, 4) not null default 0,
  booked_sales numeric(14, 2) not null default 0,
  retrieved_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (studio_id, order_date, source_row_key)
);

create index if not exists pts_reservation_bookings_studio_date_idx
  on public.pts_reservation_bookings (studio_id, order_date desc);
create index if not exists pts_reservation_bookings_event_date_idx
  on public.pts_reservation_bookings (studio_id, event_date);

alter table public.pts_reservation_bookings enable row level security;
revoke all on table public.pts_reservation_bookings from anon, authenticated;
grant select, insert, update, delete on table public.pts_reservation_bookings to service_role;
grant usage, select on sequence public.pts_reservation_bookings_id_seq to service_role;

create or replace view public.pts_reservation_bookings_reporting
with (security_invoker = true)
as
select
  booking.*,
  studio.studio_name
from public.pts_reservation_bookings booking
join public.studios studio on studio.id = booking.studio_id;

create or replace view public.pts_reservation_booking_daily
with (security_invoker = true)
as
select
  organization_id,
  brand_id,
  studio_id,
  pts_location_id,
  order_date,
  count(*) as booking_line_count,
  sum(active_reservations) as active_reservations,
  sum(refunded_reservations) as refunded_reservations,
  sum(on_hold_reservations) as on_hold_reservations,
  sum(checked_in_reservations) as checked_in_reservations,
  sum(ordered_seats) as ordered_seats,
  sum(booked_sales) as booked_sales,
  max(retrieved_at) as retrieved_at
from public.pts_reservation_bookings
group by organization_id, brand_id, studio_id, pts_location_id, order_date;

revoke all on table public.pts_reservation_bookings_reporting from anon, authenticated;
revoke all on table public.pts_reservation_booking_daily from anon, authenticated;
grant select on table public.pts_reservation_bookings_reporting to service_role;
grant select on table public.pts_reservation_booking_daily to service_role;

create or replace function public.replace_pts_reservation_booking_slice(
  p_studio_id bigint,
  p_order_date date,
  p_rows jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_count integer := 0;
begin
  if p_studio_id is null or p_order_date is null then
    raise exception 'Studio and order date are required';
  end if;
  if p_rows is null or jsonb_typeof(p_rows) <> 'array' then
    raise exception 'Reservation booking rows must be a JSON array';
  end if;
  if exists (
    select 1
    from jsonb_to_recordset(p_rows) as row_data(studio_id bigint, order_date date)
    where row_data.studio_id <> p_studio_id or row_data.order_date <> p_order_date
  ) then
    raise exception 'Reservation rows must match the requested studio/date slice';
  end if;

  delete from public.pts_reservation_bookings
  where studio_id = p_studio_id and order_date = p_order_date;

  if jsonb_array_length(p_rows) > 0 then
    insert into public.pts_reservation_bookings (
      organization_id, brand_id, studio_id, pts_location_id, order_date,
      source_row_key, order_id, confirmation, order_datetime_text,
      event_date, class_label, active_reservations, refunded_reservations,
      on_hold_reservations, checked_in_reservations, ordered_seats,
      booked_sales, retrieved_at, updated_at
    )
    select
      row_data.organization_id,
      row_data.brand_id,
      row_data.studio_id,
      row_data.pts_location_id,
      row_data.order_date,
      row_data.source_row_key,
      row_data.order_id,
      row_data.confirmation,
      row_data.order_datetime_text,
      row_data.event_date,
      row_data.class_label,
      coalesce(row_data.active_reservations, 0),
      coalesce(row_data.refunded_reservations, 0),
      coalesce(row_data.on_hold_reservations, 0),
      coalesce(row_data.checked_in_reservations, 0),
      coalesce(row_data.ordered_seats, 0),
      coalesce(row_data.booked_sales, 0),
      row_data.retrieved_at,
      now()
    from jsonb_to_recordset(p_rows) as row_data(
      organization_id bigint,
      brand_id bigint,
      studio_id bigint,
      pts_location_id text,
      order_date date,
      source_row_key text,
      order_id text,
      confirmation text,
      order_datetime_text text,
      event_date date,
      class_label text,
      active_reservations numeric,
      refunded_reservations numeric,
      on_hold_reservations numeric,
      checked_in_reservations numeric,
      ordered_seats numeric,
      booked_sales numeric,
      retrieved_at timestamptz
    );
    get diagnostics inserted_count = row_count;
  end if;

  return inserted_count;
end;
$$;

revoke all on function public.replace_pts_reservation_booking_slice(bigint, date, jsonb)
  from public, anon, authenticated;
grant execute on function public.replace_pts_reservation_booking_slice(bigint, date, jsonb)
  to service_role;

comment on table public.pts_reservation_bookings is
  'Privacy-safe PTS Reservations grid facts at studio, order date, confirmation/order, and class-line grain. Purchaser names are not collected.';
comment on view public.pts_reservation_booking_daily is
  'Daily gross booked seats and sales with current active, refunded, and held reservation counts.';
comment on function public.replace_pts_reservation_booking_slice(bigint, date, jsonb) is
  'Atomically replaces one validated studio/order-date Reservations grid slice, including valid zero-row slices.';

commit;
