begin;

create extension if not exists supabase_vault with schema vault;

create table public.meta_integration_accounts (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  account_name text not null,
  meta_user_id text not null,
  meta_user_name text,
  secret_provider text not null default 'supabase_vault',
  secret_reference text not null,
  token_expires_at timestamptz,
  data_access_expires_at timestamptz,
  connection_status text not null default 'connected',
  is_active boolean not null default true,
  last_discovered_at timestamptz,
  last_validated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, account_name),
  unique (organization_id, meta_user_id),
  constraint meta_account_name_length check (char_length(trim(account_name)) between 2 and 120),
  constraint meta_user_id_numeric check (meta_user_id ~ '^[0-9]{1,40}$'),
  constraint meta_secret_provider check (secret_provider = 'supabase_vault'),
  constraint meta_connection_status check (connection_status in ('connected', 'expiring', 'reconnect_required', 'error'))
);

create table public.meta_source_assets (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  account_id bigint not null references public.meta_integration_accounts(id) on delete cascade,
  asset_type text not null,
  asset_id text not null,
  display_name text not null,
  metadata jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  discovered_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (account_id, asset_type, asset_id),
  constraint meta_asset_type check (asset_type in ('business', 'ad_account', 'page', 'instagram_account')),
  constraint meta_asset_id_format check (asset_id ~ '^(act_)?[0-9]{1,50}$'),
  constraint meta_asset_name_length check (char_length(trim(display_name)) between 1 and 500)
);

create or replace function public.create_meta_oauth_account_with_secret(
  p_organization_id bigint,
  p_account_name text,
  p_meta_user_id text,
  p_meta_user_name text,
  p_oauth_credentials jsonb,
  p_token_expires_at timestamptz,
  p_data_access_expires_at timestamptz
) returns bigint language plpgsql security definer set search_path = public, vault, pg_temp as $$
declare account_id bigint; vault_secret_id uuid; existing_secret text;
begin
  if char_length(trim(p_account_name)) not between 2 and 120 then raise exception 'Invalid Meta account name'; end if;
  if trim(p_meta_user_id) !~ '^[0-9]{1,40}$' then raise exception 'Invalid Meta user ID'; end if;
  if jsonb_typeof(p_oauth_credentials) <> 'object' or nullif(p_oauth_credentials ->> 'access_token', '') is null
    then raise exception 'Invalid Meta OAuth credentials'; end if;

  select secret_reference into existing_secret from public.meta_integration_accounts
  where organization_id = p_organization_id and meta_user_id = trim(p_meta_user_id) for update;

  if existing_secret is null then
    insert into public.meta_integration_accounts (
      organization_id, account_name, meta_user_id, meta_user_name, secret_reference,
      token_expires_at, data_access_expires_at
    ) values (
      p_organization_id, trim(p_account_name), trim(p_meta_user_id), nullif(trim(p_meta_user_name), ''),
      'pending:' || gen_random_uuid()::text, p_token_expires_at, p_data_access_expires_at
    ) returning id into account_id;
    select vault.create_secret(p_oauth_credentials::text, 'meta-oauth-account-' || account_id::text,
      'Studio Intelligence Meta long-lived user credential') into vault_secret_id;
  else
    select id into account_id from public.meta_integration_accounts
    where organization_id = p_organization_id and meta_user_id = trim(p_meta_user_id);
    perform vault.update_secret(existing_secret::uuid, p_oauth_credentials::text,
      'meta-oauth-account-' || account_id::text, 'Studio Intelligence Meta long-lived user credential');
    vault_secret_id := existing_secret::uuid;
  end if;

  update public.meta_integration_accounts set account_name = trim(p_account_name),
    meta_user_name = nullif(trim(p_meta_user_name), ''), secret_reference = vault_secret_id::text,
    token_expires_at = p_token_expires_at, data_access_expires_at = p_data_access_expires_at,
    connection_status = 'connected', is_active = true, last_validated_at = now(), updated_at = now()
  where id = account_id;
  return account_id;
end; $$;

create or replace function public.get_meta_account_secret(p_account_id bigint)
returns jsonb language plpgsql security definer set search_path = public, vault, pg_temp as $$
declare decrypted_value text;
begin
  select secret.decrypted_secret into decrypted_value
  from public.meta_integration_accounts account
  join vault.decrypted_secrets secret on secret.id = account.secret_reference::uuid
  where account.id = p_account_id and account.is_active = true and account.secret_provider = 'supabase_vault';
  if decrypted_value is null then raise exception 'Meta account secret not found'; end if;
  return decrypted_value::jsonb;
end; $$;

create or replace function public.sync_meta_assets(p_account_id bigint, p_assets jsonb)
returns integer language plpgsql security definer set search_path = public, pg_temp as $$
declare account_record public.meta_integration_accounts%rowtype; asset_count integer;
begin
  select * into account_record from public.meta_integration_accounts where id = p_account_id and is_active = true for update;
  if account_record.id is null then raise exception 'Meta account not found'; end if;
  if jsonb_typeof(p_assets) <> 'array' then raise exception 'Meta assets must be an array'; end if;

  update public.meta_source_assets set is_active = false, updated_at = now() where account_id = p_account_id;
  insert into public.meta_source_assets (organization_id, account_id, asset_type, asset_id, display_name, metadata, is_active, discovered_at)
  select account_record.organization_id, p_account_id, trim(value ->> 'assetType'), trim(value ->> 'assetId'),
    trim(value ->> 'displayName'), coalesce(value -> 'metadata', '{}'::jsonb), true, now()
  from jsonb_array_elements(p_assets) value
  where value ->> 'assetType' in ('business', 'ad_account', 'page', 'instagram_account')
    and trim(value ->> 'assetId') ~ '^(act_)?[0-9]{1,50}$' and nullif(trim(value ->> 'displayName'), '') is not null
  on conflict (account_id, asset_type, asset_id) do update set display_name = excluded.display_name,
    metadata = excluded.metadata, is_active = true, discovered_at = now(), updated_at = now();

  update public.meta_integration_accounts set last_discovered_at = now(), last_validated_at = now(),
    connection_status = 'connected', updated_at = now() where id = p_account_id;
  select count(*) into asset_count from public.meta_source_assets where account_id = p_account_id and is_active = true;
  return asset_count;
end; $$;

create or replace function public.map_meta_asset(
  p_organization_id bigint, p_account_id bigint, p_asset_type text, p_asset_id text, p_studio_id bigint
) returns bigint language plpgsql security definer set search_path = public, pg_temp as $$
declare asset_record public.meta_source_assets%rowtype; target_brand_id bigint; mapping_id bigint; integration_kind text;
begin
  if p_asset_type not in ('ad_account', 'page', 'instagram_account') then raise exception 'Unsupported Meta mapping asset'; end if;
  select * into asset_record from public.meta_source_assets where organization_id = p_organization_id
    and account_id = p_account_id and asset_type = p_asset_type and asset_id = trim(p_asset_id) and is_active = true;
  if asset_record.id is null then raise exception 'Meta asset not found'; end if;
  select brand_id into target_brand_id from public.studios where id = p_studio_id and organization_id = p_organization_id and active = true;
  if target_brand_id is null then raise exception 'Studio not found'; end if;
  integration_kind := case p_asset_type when 'ad_account' then 'meta_ads' when 'page' then 'meta_page' else 'meta_instagram' end;

  select id into mapping_id from public.studio_integrations where organization_id = p_organization_id
    and integration_type = integration_kind and (studio_id = p_studio_id or external_id = asset_record.asset_id)
    and is_active = true limit 1 for update;
  if mapping_id is null then
    insert into public.studio_integrations (organization_id, brand_id, studio_id, integration_type,
      integration_name, external_id, is_active, configuration)
    values (p_organization_id, target_brand_id, p_studio_id, integration_kind, asset_record.display_name,
      asset_record.asset_id, true, jsonb_build_object('meta_account_id', p_account_id, 'asset_type', p_asset_type))
    returning id into mapping_id;
  else
    update public.studio_integrations set brand_id = target_brand_id, studio_id = p_studio_id,
      integration_name = asset_record.display_name, external_id = asset_record.asset_id,
      configuration = coalesce(configuration, '{}'::jsonb) || jsonb_build_object('meta_account_id', p_account_id, 'asset_type', p_asset_type)
    where id = mapping_id;
  end if;
  return mapping_id;
end; $$;

create view public.meta_collection_accounts as
select id as account_id, organization_id, account_name, meta_user_id, token_expires_at,
  data_access_expires_at, connection_status, last_discovered_at, last_validated_at
from public.meta_integration_accounts where is_active = true;

create view public.meta_collection_targets as
select account.id as account_id, mapping.organization_id, mapping.brand_id, mapping.studio_id,
  studio.studio_code, studio.studio_name, studio.timezone, mapping.id as integration_id,
  asset.asset_type, asset.asset_id, asset.display_name as asset_name, asset.metadata
from public.meta_integration_accounts account
join public.studio_integrations mapping on mapping.organization_id = account.organization_id
  and mapping.integration_type in ('meta_ads', 'meta_page', 'meta_instagram') and mapping.is_active = true
  and (mapping.configuration ->> 'meta_account_id')::bigint = account.id
join public.studios studio on studio.id = mapping.studio_id and studio.active = true
join public.meta_source_assets asset on asset.account_id = account.id and asset.asset_id = mapping.external_id
  and asset.asset_type = mapping.configuration ->> 'asset_type' and asset.is_active = true
where account.is_active = true;

alter table public.meta_integration_accounts enable row level security;
alter table public.meta_source_assets enable row level security;
revoke all on table public.meta_integration_accounts, public.meta_source_assets,
  public.meta_collection_accounts, public.meta_collection_targets from public, anon, authenticated;
grant select, insert, update, delete on table public.meta_integration_accounts, public.meta_source_assets to service_role;
grant select on table public.meta_collection_accounts, public.meta_collection_targets to service_role;
grant usage, select on sequence public.meta_integration_accounts_id_seq, public.meta_source_assets_id_seq to service_role;
revoke all on function public.create_meta_oauth_account_with_secret(bigint,text,text,text,jsonb,timestamptz,timestamptz),
  public.get_meta_account_secret(bigint), public.sync_meta_assets(bigint,jsonb),
  public.map_meta_asset(bigint,bigint,text,text,bigint) from public, anon, authenticated;
grant execute on function public.create_meta_oauth_account_with_secret(bigint,text,text,text,jsonb,timestamptz,timestamptz),
  public.get_meta_account_secret(bigint), public.sync_meta_assets(bigint,jsonb),
  public.map_meta_asset(bigint,bigint,text,text,bigint) to service_role;

comment on table public.meta_integration_accounts is 'Tenant-scoped Meta owner OAuth connections with long-lived user credentials stored only in Supabase Vault.';
comment on table public.meta_source_assets is 'Businesses, ad accounts, Facebook Pages, and Instagram professional accounts discovered through an owner Meta connection.';
comment on view public.meta_collection_targets is 'Service-only Meta connection, asset, and studio routing without secret values.';

commit;
