begin;

create table if not exists public.marketing_strategy_changes (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  studio_id bigint references public.studios(id) on delete cascade,
  platform text not null default 'eulerity'
    check (platform in ('eulerity')),
  effective_date date not null,
  change_type text not null
    check (change_type in (
      'budget', 'targeting', 'creative', 'bidding',
      'campaign_structure', 'offer', 'other'
    )),
  title text not null check (char_length(title) between 1 and 120),
  notes text check (notes is null or char_length(notes) <= 1000),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists marketing_strategy_changes_org_date_idx
  on public.marketing_strategy_changes (organization_id, effective_date desc);

create index if not exists marketing_strategy_changes_studio_date_idx
  on public.marketing_strategy_changes (studio_id, effective_date desc)
  where studio_id is not null;

create or replace function public.validate_marketing_strategy_change_studio()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.studio_id is not null and not exists (
    select 1
    from public.studios studio
    where studio.id = new.studio_id
      and studio.organization_id = new.organization_id
      and studio.active is true
  ) then
    raise exception 'Strategy-change studio must be active and belong to the organization';
  end if;

  return new;
end;
$$;

drop trigger if exists validate_marketing_strategy_change_studio
  on public.marketing_strategy_changes;
create trigger validate_marketing_strategy_change_studio
before insert or update of organization_id, studio_id
on public.marketing_strategy_changes
for each row execute function public.validate_marketing_strategy_change_studio();

alter table public.marketing_strategy_changes enable row level security;

revoke all on table public.marketing_strategy_changes from anon, authenticated;
grant select, insert, update, delete
  on table public.marketing_strategy_changes to service_role;
grant usage, select on sequence public.marketing_strategy_changes_id_seq
  to service_role;

comment on table public.marketing_strategy_changes is
  'Tenant-scoped dated annotations for interpreting paid-marketing performance changes. Notes must not contain customer data or credentials.';

commit;
