begin;

insert into public.pts_product_reporting_mappings (
  organization_id,
  source_field,
  source_value,
  product_group,
  department,
  priority
)
select organization_id, source_field, source_value, product_group, department, priority
from (
  values
    (1::bigint, 'subcategory'::text, 'Miscellaneous Drinks'::text, 'Misc Drinks'::text, 'Food & Beverage'::text, 50),
    (1::bigint, 'subcategory'::text, 'Alcohol Specials'::text, 'Alcohol Specials'::text, 'Food & Beverage'::text, 50)
) as mapping(
  organization_id,
  source_field,
  source_value,
  product_group,
  department,
  priority
)
where exists (
  select 1 from public.organizations where id = mapping.organization_id
)
on conflict (organization_id, source_field, source_value)
do update set
  product_group = excluded.product_group,
  department = excluded.department,
  priority = excluded.priority,
  is_active = true,
  updated_at = now();

create table if not exists public.pts_class_type_sales_daily (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  brand_id bigint not null references public.brands(id) on delete cascade,
  studio_id bigint not null references public.studios(id) on delete cascade,
  pts_location_id text not null,
  report_date date not null,
  source_class_type text not null,
  class_event_count integer not null default 0,
  seats_sold numeric(12, 4) not null default 0,
  capacity numeric(12, 4) not null default 0,
  class_sales numeric(14, 2) not null default 0,
  source_product_sales numeric(14, 2) not null default 0,
  fee_sales numeric(14, 2) not null default 0,
  source_net_sales numeric(14, 2) not null default 0,
  retrieved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (studio_id, report_date, source_class_type)
);

create table if not exists public.pts_product_sales_daily (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  brand_id bigint not null references public.brands(id) on delete cascade,
  studio_id bigint not null references public.studios(id) on delete cascade,
  pts_location_id text not null,
  report_date date not null,
  category text not null,
  subcategory text not null default '',
  item_name text not null,
  quantity numeric(12, 4) not null default 0,
  gross_sales numeric(14, 2) not null default 0,
  net_sales numeric(14, 2) not null default 0,
  tax numeric(14, 2) not null default 0,
  alcohol_tax numeric(14, 2) not null default 0,
  nat_sales numeric(14, 2) not null default 0,
  retrieved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (studio_id, report_date, category, subcategory, item_name)
);

create index if not exists pts_class_type_sales_daily_studio_date_idx
  on public.pts_class_type_sales_daily (studio_id, report_date desc);
create index if not exists pts_product_sales_daily_studio_date_idx
  on public.pts_product_sales_daily (studio_id, report_date desc);
create index if not exists pts_product_sales_daily_category_date_idx
  on public.pts_product_sales_daily (category, subcategory, report_date desc);

alter table public.pts_class_type_sales_daily enable row level security;
alter table public.pts_product_sales_daily enable row level security;

revoke all on table public.pts_class_type_sales_daily from anon, authenticated;
revoke all on table public.pts_product_sales_daily from anon, authenticated;
grant select, insert, update, delete on table public.pts_class_type_sales_daily to service_role;
grant select, insert, update, delete on table public.pts_product_sales_daily to service_role;
grant usage, select on sequence public.pts_class_type_sales_daily_id_seq to service_role;
grant usage, select on sequence public.pts_product_sales_daily_id_seq to service_role;

create or replace view public.pts_class_type_sales_daily_reporting
with (security_invoker = true)
as
select
  daily.organization_id,
  daily.brand_id,
  daily.studio_id,
  daily.pts_location_id,
  daily.report_date,
  daily.source_class_type,
  coalesce(mapping.reporting_class_type, 'Unmapped') as reporting_class_type,
  daily.class_event_count,
  daily.seats_sold,
  daily.capacity,
  daily.class_sales,
  daily.source_product_sales,
  daily.fee_sales,
  daily.source_net_sales,
  case when mapping.id is null then 'unmapped' else 'mapped' end as mapping_status,
  daily.retrieved_at,
  daily.updated_at
from public.pts_class_type_sales_daily daily
left join public.pts_class_type_mappings mapping
  on mapping.organization_id = daily.organization_id
 and lower(trim(mapping.source_class_type)) = lower(trim(daily.source_class_type))
 and mapping.is_active;

create or replace view public.pts_product_sales_daily_reporting
with (security_invoker = true)
as
select
  daily.*,
  mapping.product_group,
  mapping.department,
  case when mapping.id is null then 'unmapped' else 'mapped' end as mapping_status
from public.pts_product_sales_daily daily
left join lateral (
  select candidate.*
  from public.pts_product_reporting_mappings candidate
  where candidate.organization_id = daily.organization_id
    and candidate.is_active
    and lower(trim(candidate.source_value)) = lower(trim(
      case candidate.source_field
        when 'category' then daily.category
        when 'subcategory' then daily.subcategory
        when 'item_name' then daily.item_name
      end
    ))
  order by candidate.priority, candidate.id
  limit 1
) mapping on true;

create or replace view public.pts_operations_daily
with (security_invoker = true)
as
with class_totals as (
  select
    organization_id,
    brand_id,
    studio_id,
    report_date,
    sum(class_event_count) as class_event_count,
    sum(seats_sold) as seats_sold,
    sum(capacity) as capacity,
    sum(class_sales) as class_sales,
    sum(fee_sales) as fee_sales
  from public.pts_class_type_sales_daily
  group by organization_id, brand_id, studio_id, report_date
),
product_totals as (
  select
    organization_id,
    brand_id,
    studio_id,
    report_date,
    sum(net_sales) as product_sales,
    sum(net_sales) filter (where department = 'Food & Beverage') as food_and_beverage_sales,
    sum(net_sales) filter (where department = 'Other Products') as other_product_sales,
    sum(net_sales) filter (where mapping_status = 'unmapped') as unmapped_product_sales
  from public.pts_product_sales_daily_reporting
  group by organization_id, brand_id, studio_id, report_date
),
dates as (
  select organization_id, brand_id, studio_id, report_date
  from class_totals
  union
  select organization_id, brand_id, studio_id, report_date
  from product_totals
)
select
  dates.organization_id,
  dates.brand_id,
  dates.studio_id,
  dates.report_date,
  coalesce(class_totals.class_event_count, 0) as class_event_count,
  coalesce(class_totals.seats_sold, 0) as seats_sold,
  coalesce(class_totals.capacity, 0) as capacity,
  coalesce(class_totals.class_sales, 0) as class_sales,
  coalesce(class_totals.fee_sales, 0) as fee_sales,
  coalesce(product_totals.product_sales, 0) as product_sales,
  coalesce(product_totals.food_and_beverage_sales, 0) as food_and_beverage_sales,
  coalesce(product_totals.other_product_sales, 0) as other_product_sales,
  coalesce(product_totals.unmapped_product_sales, 0) as unmapped_product_sales,
  coalesce(class_totals.class_sales, 0)
    + coalesce(class_totals.fee_sales, 0)
    + coalesce(product_totals.product_sales, 0) as total_sales,
  case
    when coalesce(class_totals.seats_sold, 0) = 0 then 0
    else (
      coalesce(class_totals.class_sales, 0)
      + coalesce(class_totals.fee_sales, 0)
      + coalesce(product_totals.product_sales, 0)
    ) / class_totals.seats_sold
  end as revenue_per_seat,
  case
    when coalesce(class_totals.seats_sold, 0) = 0 then 0
    else coalesce(product_totals.food_and_beverage_sales, 0)
      / class_totals.seats_sold
  end as food_and_beverage_per_seat
from dates
left join class_totals using (organization_id, brand_id, studio_id, report_date)
left join product_totals using (organization_id, brand_id, studio_id, report_date);

revoke all on table public.pts_class_type_sales_daily_reporting from anon, authenticated;
revoke all on table public.pts_product_sales_daily_reporting from anon, authenticated;
revoke all on table public.pts_operations_daily from anon, authenticated;
grant select on table public.pts_class_type_sales_daily_reporting to service_role;
grant select on table public.pts_product_sales_daily_reporting to service_role;
grant select on table public.pts_operations_daily to service_role;

comment on table public.pts_class_type_sales_daily is
  'Daily PTS class metrics grouped by studio, event date, and raw source class type.';
comment on table public.pts_product_sales_daily is
  'Daily PTS Product Sales metrics grouped by studio, sale date, category, subcategory, and item. Customer data is not stored.';
comment on view public.pts_operations_daily is
  'PTS daily operations totals derived from class revenue plus fees plus authoritative Product Sales detail, avoiding duplicated class-report product amounts.';

commit;
