-- Encrypted, tenant-scoped MNTN API accounts and advertiser mappings.
-- The API key is readable only through the service-role broker function.

begin;

create extension if not exists supabase_vault with schema vault;

create table public.mntn_integration_accounts (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  account_name text not null,
  secret_provider text not null default 'supabase_vault',
  secret_reference text not null,
  is_active boolean not null default true,
  last_validated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, account_name),
  constraint mntn_account_name_length check (char_length(trim(account_name)) between 2 and 120),
  constraint mntn_secret_provider check (secret_provider = 'supabase_vault')
);

create index mntn_accounts_org_active_idx
  on public.mntn_integration_accounts (organization_id, is_active);

create or replace function public.create_mntn_connection_with_secret(
  p_organization_id bigint,
  p_account_name text,
  p_api_key text,
  p_studio_id bigint,
  p_advertiser_id text
)
returns bigint
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare
  account_id bigint;
  vault_secret_id uuid;
  target_brand_id bigint;
begin
  if char_length(trim(p_account_name)) not between 2 and 120 then raise exception 'Invalid MNTN account name'; end if;
  if char_length(trim(p_api_key)) not between 8 and 2048 then raise exception 'Invalid MNTN API key'; end if;
  if trim(p_advertiser_id) !~ '^[0-9]{1,20}$' then raise exception 'Invalid MNTN advertiser ID'; end if;

  select brand_id into target_brand_id
  from public.studios
  where id = p_studio_id and organization_id = p_organization_id and active = true;
  if target_brand_id is null then raise exception 'Studio not found'; end if;

  if exists (
    select 1 from public.studio_integrations
    where organization_id = p_organization_id
      and integration_type = 'mntn'
      and (studio_id = p_studio_id or external_id = trim(p_advertiser_id))
      and is_active = true
  ) then raise exception 'Studio or advertiser already has an active MNTN mapping'; end if;

  insert into public.mntn_integration_accounts (
    organization_id, account_name, secret_reference
  ) values (
    p_organization_id, trim(p_account_name), 'pending:' || gen_random_uuid()::text
  ) returning id into account_id;

  select vault.create_secret(
    jsonb_build_object('apiKey', trim(p_api_key))::text,
    'mntn-account-' || account_id::text,
    'Studio Intelligence MNTN Reporting API key'
  ) into vault_secret_id;

  update public.mntn_integration_accounts
  set secret_reference = vault_secret_id::text, updated_at = now()
  where id = account_id;

  insert into public.studio_integrations (
    organization_id, brand_id, studio_id, integration_type,
    integration_name, external_id, is_active, configuration
  ) values (
    p_organization_id, target_brand_id, p_studio_id, 'mntn',
    trim(p_account_name), trim(p_advertiser_id), true,
    jsonb_build_object(
      'mntn_account_id', account_id,
      'attribution_window_days', 30,
      'refresh_window_days', 35
    )
  );

  return account_id;
end;
$$;

create or replace function public.replace_mntn_account_secret(
  p_organization_id bigint,
  p_account_id bigint,
  p_api_key text
)
returns void
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare vault_secret_id uuid;
begin
  if char_length(trim(p_api_key)) not between 8 and 2048 then raise exception 'Invalid MNTN API key'; end if;
  select secret_reference::uuid into vault_secret_id
  from public.mntn_integration_accounts
  where id = p_account_id and organization_id = p_organization_id
    and secret_provider = 'supabase_vault' and is_active = true
    and secret_reference ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$';
  if vault_secret_id is null then raise exception 'MNTN Vault account not found'; end if;

  perform vault.update_secret(
    vault_secret_id,
    jsonb_build_object('apiKey', trim(p_api_key))::text,
    'mntn-account-' || p_account_id::text,
    'Studio Intelligence MNTN Reporting API key'
  );
  update public.mntn_integration_accounts
  set last_validated_at = null, updated_at = now()
  where id = p_account_id and organization_id = p_organization_id;
end;
$$;

create or replace function public.get_mntn_account_secret(p_account_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare decrypted_value text;
begin
  select secret.decrypted_secret into decrypted_value
  from public.mntn_integration_accounts account
  join vault.decrypted_secrets secret on secret.id = account.secret_reference::uuid
  where account.id = p_account_id and account.secret_provider = 'supabase_vault'
    and account.is_active = true;
  if decrypted_value is null then raise exception 'MNTN account secret not found'; end if;
  return decrypted_value::jsonb;
end;
$$;

create or replace function public.mark_mntn_account_validated(p_account_id bigint)
returns void language sql security definer set search_path = public, pg_temp as $$
  update public.mntn_integration_accounts
  set last_validated_at = now(), updated_at = now()
  where id = p_account_id and is_active = true;
$$;

create or replace view public.mntn_collection_targets as
select
  account.organization_id,
  account.id as account_id,
  studio.brand_id,
  studio.id as studio_id,
  studio.studio_code,
  studio.studio_name,
  studio.timezone,
  mapping.id as integration_id,
  mapping.external_id as advertiser_id,
  coalesce((mapping.configuration ->> 'refresh_window_days')::integer, 35) as refresh_window_days
from public.mntn_integration_accounts account
join public.studio_integrations mapping
  on mapping.organization_id = account.organization_id
 and mapping.integration_type = 'mntn' and mapping.is_active = true
 and mapping.configuration ->> 'mntn_account_id' = account.id::text
join public.studios studio
  on studio.id = mapping.studio_id and studio.organization_id = account.organization_id
 and studio.active = true
where account.is_active = true;

alter table public.mntn_integration_accounts enable row level security;
revoke all on table public.mntn_integration_accounts, public.mntn_collection_targets from public, anon, authenticated;
grant select, insert, update, delete on table public.mntn_integration_accounts to service_role;
grant usage, select on sequence public.mntn_integration_accounts_id_seq to service_role;
grant select on table public.mntn_collection_targets to service_role;

revoke all on function public.create_mntn_connection_with_secret(bigint, text, text, bigint, text),
  public.replace_mntn_account_secret(bigint, bigint, text),
  public.get_mntn_account_secret(bigint), public.mark_mntn_account_validated(bigint)
  from public, anon, authenticated;
grant execute on function public.create_mntn_connection_with_secret(bigint, text, text, bigint, text),
  public.replace_mntn_account_secret(bigint, bigint, text),
  public.get_mntn_account_secret(bigint), public.mark_mntn_account_validated(bigint)
  to service_role;

comment on table public.mntn_integration_accounts is
  'Tenant-scoped MNTN account metadata. API keys are stored only in Supabase Vault.';
comment on view public.mntn_collection_targets is
  'Service-only MNTN advertiser collection routing without secret values.';

commit;
