begin;

create table if not exists public.pts_upcoming_class_snapshots (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  brand_id bigint not null references public.brands(id) on delete cascade,
  studio_id bigint not null references public.studios(id) on delete cascade,
  pts_location_id text not null,
  snapshot_date date not null,
  source_event_key text not null,
  event_date date not null,
  painting text,
  class_time timestamptz,
  room text,
  class_type text,
  seats_sold numeric(12, 4) not null default 0,
  capacity numeric(12, 4) not null default 0,
  percent_full numeric(10, 4) not null default 0,
  lead_time_average numeric(10, 4),
  class_sales numeric(14, 2) not null default 0,
  product_sales numeric(14, 2) not null default 0,
  fee_sales numeric(14, 2) not null default 0,
  net_sales numeric(14, 2) not null default 0,
  retrieved_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (studio_id, snapshot_date, source_event_key)
);

create index if not exists pts_upcoming_snapshots_studio_snapshot_idx
  on public.pts_upcoming_class_snapshots (studio_id, snapshot_date desc);
create index if not exists pts_upcoming_snapshots_event_date_idx
  on public.pts_upcoming_class_snapshots (studio_id, event_date, class_time);
create index if not exists pts_upcoming_snapshots_event_history_idx
  on public.pts_upcoming_class_snapshots (studio_id, source_event_key, snapshot_date);

alter table public.pts_upcoming_class_snapshots enable row level security;
revoke all on table public.pts_upcoming_class_snapshots from anon, authenticated;
grant select, insert, update, delete on table public.pts_upcoming_class_snapshots to service_role;
grant usage, select on sequence public.pts_upcoming_class_snapshots_id_seq to service_role;

create or replace view public.pts_upcoming_class_snapshots_reporting
with (security_invoker = true)
as
with mapped as (
  select
    snapshot.*,
    snapshot.class_type as source_class_type,
    coalesce(mapping.reporting_class_type, 'Unmapped') as reporting_class_type,
    case when mapping.id is null then 'unmapped' else 'mapped' end as mapping_status,
    lag(snapshot.snapshot_date) over event_history as previous_snapshot_date,
    lag(snapshot.seats_sold) over event_history as previous_seats_sold,
    lag(snapshot.class_sales) over event_history as previous_class_sales,
    lag(snapshot.fee_sales) over event_history as previous_fee_sales
  from public.pts_upcoming_class_snapshots snapshot
  left join public.pts_class_type_mappings mapping
    on mapping.organization_id = snapshot.organization_id
   and lower(trim(mapping.source_class_type)) = lower(trim(snapshot.class_type))
   and mapping.is_active
  window event_history as (
    partition by snapshot.studio_id, snapshot.source_event_key
    order by snapshot.snapshot_date
  )
)
select
  mapped.*,
  greatest(mapped.capacity - mapped.seats_sold, 0) as seats_remaining,
  case
    when mapped.capacity > 0 then mapped.seats_sold / mapped.capacity * 100
    else 0
  end as capacity_percent,
  case
    when mapped.previous_snapshot_date = mapped.snapshot_date - 1
      then mapped.seats_sold - mapped.previous_seats_sold
    else null
  end as seats_pickup,
  case
    when mapped.previous_snapshot_date = mapped.snapshot_date - 1
      then (mapped.class_sales + mapped.fee_sales)
         - (mapped.previous_class_sales + mapped.previous_fee_sales)
    else null
  end as revenue_pickup
from mapped;

create or replace view public.pts_upcoming_classes_current
with (security_invoker = true)
as
with latest_snapshot as (
  select studio_id, max(snapshot_date) as snapshot_date
  from public.pts_upcoming_class_snapshots
  group by studio_id
)
select reporting.*
from public.pts_upcoming_class_snapshots_reporting reporting
join latest_snapshot
  on latest_snapshot.studio_id = reporting.studio_id
 and latest_snapshot.snapshot_date = reporting.snapshot_date
where reporting.event_date >= reporting.snapshot_date;

revoke all on table public.pts_upcoming_class_snapshots_reporting from anon, authenticated;
revoke all on table public.pts_upcoming_classes_current from anon, authenticated;
grant select on table public.pts_upcoming_class_snapshots_reporting to service_role;
grant select on table public.pts_upcoming_classes_current to service_role;

comment on table public.pts_upcoming_class_snapshots is
  'Daily event-grain snapshots of future PTS Class Sales. A workflow replaces one studio/snapshot-date slice on rerun while preserving prior snapshot dates.';
comment on view public.pts_upcoming_classes_current is
  'Latest complete future-class snapshot per studio with governed class types, capacity, and consecutive-day net pickup metrics.';

commit;
