-- PTS browser-automation configuration and Sales Report warehouse facts.
-- Credentials are never stored in these tables; only protected secret references.

begin;

create table if not exists public.pts_integration_accounts (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  account_name text not null,
  secret_provider text not null,
  secret_reference text not null,
  is_active boolean not null default true,
  last_validated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, secret_reference)
);

create table if not exists public.pts_sales_daily_summary (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  brand_id bigint not null references public.brands(id) on delete cascade,
  studio_id bigint not null references public.studios(id) on delete cascade,
  pts_location_id text not null,
  report_date date not null,
  gross_sales numeric(14, 2) not null default 0,
  refunds numeric(14, 2) not null default 0,
  reschedules numeric(14, 2) not null default 0,
  discounts numeric(14, 2) not null default 0,
  net_sales numeric(14, 2) not null default 0,
  class_sales numeric(14, 2) not null default 0,
  alcohol_sales numeric(14, 2) not null default 0,
  other_product_sales numeric(14, 2) not null default 0,
  taxes numeric(14, 2) not null default 0,
  nat_sales numeric(14, 2) not null default 0,
  seats_sold integer not null default 0,
  attendance_percent numeric(8, 4) not null default 0,
  lead_time_average_days numeric(10, 4) not null default 0,
  retrieved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (studio_id, report_date)
);

create table if not exists public.pts_class_sales_daily (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  brand_id bigint not null references public.brands(id) on delete cascade,
  studio_id bigint not null references public.studios(id) on delete cascade,
  pts_location_id text not null,
  report_date date not null,
  source_row_hash text not null,
  painting text,
  class_time timestamptz,
  room text,
  class_type text,
  seats_sold numeric(12, 4) not null default 0,
  capacity numeric(12, 4) not null default 0,
  percent_full numeric(10, 4) not null default 0,
  lead_time_average numeric(10, 4),
  class_sales numeric(14, 2) not null default 0,
  product_sales numeric(14, 2) not null default 0,
  fee_sales numeric(14, 2) not null default 0,
  net_sales numeric(14, 2) not null default 0,
  raw_payload jsonb not null default '{}'::jsonb,
  retrieved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (studio_id, report_date, source_row_hash)
);

create table if not exists public.pts_non_class_sales_items (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  brand_id bigint not null references public.brands(id) on delete cascade,
  studio_id bigint not null references public.studios(id) on delete cascade,
  pts_location_id text not null,
  report_date date not null,
  source_row_hash text not null,
  order_number text,
  sale_date timestamptz,
  order_date timestamptz,
  sale_or_order text,
  source text,
  payment_method text,
  item_type text,
  category text,
  subcategory text,
  item_name text,
  quantity numeric(12, 4) not null default 0,
  gross_sales numeric(14, 2) not null default 0,
  net_sales numeric(14, 2) not null default 0,
  tax numeric(14, 2) not null default 0,
  alcohol_tax numeric(14, 2) not null default 0,
  nat_sales numeric(14, 2) not null default 0,
  raw_payload jsonb not null default '{}'::jsonb,
  retrieved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (studio_id, report_date, source_row_hash)
);

create index if not exists pts_sales_summary_org_date_idx
  on public.pts_sales_daily_summary (organization_id, report_date desc);
create index if not exists pts_class_sales_studio_date_idx
  on public.pts_class_sales_daily (studio_id, report_date desc);
create index if not exists pts_non_class_sales_studio_date_idx
  on public.pts_non_class_sales_items (studio_id, report_date desc);
create index if not exists pts_non_class_sales_category_date_idx
  on public.pts_non_class_sales_items (category, report_date desc);

alter table public.pts_integration_accounts enable row level security;
alter table public.pts_sales_daily_summary enable row level security;
alter table public.pts_class_sales_daily enable row level security;
alter table public.pts_non_class_sales_items enable row level security;

revoke all on table public.pts_integration_accounts from anon, authenticated;
revoke all on table public.pts_sales_daily_summary from anon, authenticated;
revoke all on table public.pts_class_sales_daily from anon, authenticated;
revoke all on table public.pts_non_class_sales_items from anon, authenticated;

grant select, insert, update, delete on table public.pts_integration_accounts to service_role;
grant select, insert, update, delete on table public.pts_sales_daily_summary to service_role;
grant select, insert, update, delete on table public.pts_class_sales_daily to service_role;
grant select, insert, update, delete on table public.pts_non_class_sales_items to service_role;

grant usage, select on sequence public.pts_integration_accounts_id_seq to service_role;
grant usage, select on sequence public.pts_sales_daily_summary_id_seq to service_role;
grant usage, select on sequence public.pts_class_sales_daily_id_seq to service_role;
grant usage, select on sequence public.pts_non_class_sales_items_id_seq to service_role;

insert into public.pts_integration_accounts (
  organization_id,
  account_name,
  secret_provider,
  secret_reference
)
select 1, 'Duff PTS account', 'railway', 'PTS_USERNAME+PTS_PASSWORD'
where exists (select 1 from public.organizations where id = 1)
on conflict (organization_id, secret_reference) do nothing;

with mappings(studio_id, location_id, location_name) as (
  values
    (1::bigint, '19'::text, 'St. Matthews'::text),
    (2::bigint, '228'::text, 'Short North'::text),
    (3::bigint, '198'::text, 'Gilbert'::text),
    (4::bigint, '243'::text, 'Jeffersonville'::text)
)
insert into public.studio_integrations (
  organization_id,
  brand_id,
  studio_id,
  integration_type,
  integration_name,
  external_id,
  is_active,
  configuration
)
select
  s.organization_id,
  s.brand_id,
  s.id,
  'pts',
  mappings.location_name,
  mappings.location_id,
  true,
  jsonb_build_object(
    'credential_reference', 'PTS_USERNAME+PTS_PASSWORD',
    'reports', jsonb_build_array('sales')
  )
from mappings
join public.studios s on s.id = mappings.studio_id
where not exists (
  select 1
  from public.studio_integrations existing
  where existing.studio_id = mappings.studio_id
    and existing.integration_type = 'pts'
);

comment on table public.pts_integration_accounts is
  'PTS account metadata and protected secret references only. Never store usernames or passwords here.';
comment on table public.pts_non_class_sales_items is
  'PTS non-class sales line items with customer names deliberately excluded for data minimization.';

commit;
