-- Vault-backed Eulerity accounts, discovered source locations, and
-- configuration-driven studio mappings.

begin;

create extension if not exists supabase_vault with schema vault;

create table public.eulerity_integration_accounts (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  account_name text not null,
  secret_provider text not null default 'supabase_vault',
  secret_reference text not null,
  single_studio_id bigint references public.studios(id) on delete restrict,
  is_active boolean not null default true,
  last_discovered_at timestamptz,
  last_validated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, account_name),
  constraint eulerity_account_name_length check (char_length(trim(account_name)) between 2 and 120),
  constraint eulerity_secret_provider check (secret_provider = 'supabase_vault')
);

create table public.eulerity_source_locations (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  account_id bigint not null references public.eulerity_integration_accounts(id) on delete cascade,
  source_key text not null,
  display_name text not null,
  is_active boolean not null default true,
  discovered_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (account_id, source_key),
  constraint eulerity_source_key_length check (char_length(trim(source_key)) between 1 and 500),
  constraint eulerity_display_name_length check (char_length(trim(display_name)) between 1 and 500)
);

create index eulerity_accounts_org_active_idx
  on public.eulerity_integration_accounts (organization_id, is_active);
create index eulerity_locations_account_active_idx
  on public.eulerity_source_locations (account_id, is_active);

create or replace function public.create_eulerity_account_with_secret(
  p_organization_id bigint,
  p_account_name text,
  p_email text,
  p_password text,
  p_single_studio_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare
  account_id bigint;
  vault_secret_id uuid;
begin
  if char_length(trim(p_account_name)) not between 2 and 120 then raise exception 'Invalid Eulerity account name'; end if;
  if char_length(trim(p_email)) not between 3 and 254 then raise exception 'Invalid Eulerity email'; end if;
  if char_length(p_password) not between 1 and 1024 then raise exception 'Invalid Eulerity password'; end if;
  if p_single_studio_id is not null and not exists (
    select 1 from public.studios
    where id = p_single_studio_id and organization_id = p_organization_id and active = true
  ) then raise exception 'Single-location studio not found'; end if;

  insert into public.eulerity_integration_accounts (
    organization_id, account_name, secret_reference, single_studio_id
  ) values (
    p_organization_id, trim(p_account_name), 'pending:' || gen_random_uuid()::text, p_single_studio_id
  ) returning id into account_id;

  select vault.create_secret(
    jsonb_build_object('email', lower(trim(p_email)), 'password', p_password)::text,
    'eulerity-account-' || account_id::text,
    'Studio Intelligence Eulerity browser credentials'
  ) into vault_secret_id;

  update public.eulerity_integration_accounts
  set secret_reference = vault_secret_id::text, updated_at = now()
  where id = account_id;

  return account_id;
end;
$$;

create or replace function public.replace_eulerity_account_secret(
  p_organization_id bigint,
  p_account_id bigint,
  p_email text,
  p_password text
)
returns void
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare vault_secret_id uuid;
begin
  if char_length(trim(p_email)) not between 3 and 254 then raise exception 'Invalid Eulerity email'; end if;
  if char_length(p_password) not between 1 and 1024 then raise exception 'Invalid Eulerity password'; end if;

  select secret_reference::uuid into vault_secret_id
  from public.eulerity_integration_accounts
  where id = p_account_id and organization_id = p_organization_id
    and secret_provider = 'supabase_vault' and is_active = true
    and secret_reference ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$';
  if vault_secret_id is null then raise exception 'Eulerity Vault account not found'; end if;

  perform vault.update_secret(
    vault_secret_id,
    jsonb_build_object('email', lower(trim(p_email)), 'password', p_password)::text,
    'eulerity-account-' || p_account_id::text,
    'Studio Intelligence Eulerity browser credentials'
  );
  update public.eulerity_integration_accounts
  set last_validated_at = null, updated_at = now()
  where id = p_account_id and organization_id = p_organization_id;
end;
$$;

create or replace function public.get_eulerity_account_secret(p_account_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare decrypted_value text;
begin
  select secret.decrypted_secret into decrypted_value
  from public.eulerity_integration_accounts account
  join vault.decrypted_secrets secret on secret.id = account.secret_reference::uuid
  where account.id = p_account_id and account.secret_provider = 'supabase_vault'
    and account.is_active = true;
  if decrypted_value is null then raise exception 'Eulerity account secret not found'; end if;
  return decrypted_value::jsonb;
end;
$$;

create or replace function public.sync_eulerity_locations(
  p_account_id bigint,
  p_locations jsonb
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  account_record public.eulerity_integration_accounts%rowtype;
  location_count integer;
  only_location record;
  target_brand_id bigint;
  mapping_id bigint;
begin
  select * into account_record from public.eulerity_integration_accounts
  where id = p_account_id and is_active = true for update;
  if account_record.id is null then raise exception 'Eulerity account not found'; end if;
  if jsonb_typeof(p_locations) <> 'array' then raise exception 'Eulerity locations must be an array'; end if;

  update public.eulerity_source_locations set is_active = false, updated_at = now()
  where account_id = p_account_id;

  insert into public.eulerity_source_locations (
    organization_id, account_id, source_key, display_name, is_active, discovered_at
  )
  select account_record.organization_id, p_account_id, trim(value ->> 'sourceKey'),
    trim(value ->> 'displayName'), true, now()
  from jsonb_array_elements(p_locations) value
  where nullif(trim(value ->> 'sourceKey'), '') is not null
    and nullif(trim(value ->> 'displayName'), '') is not null
  on conflict (account_id, source_key) do update set
    display_name = excluded.display_name,
    is_active = true,
    discovered_at = now(),
    updated_at = now();

  update public.eulerity_integration_accounts
  set last_discovered_at = now(), last_validated_at = now(), updated_at = now()
  where id = p_account_id;

  select count(*) into location_count from public.eulerity_source_locations
  where account_id = p_account_id and is_active = true;

  if location_count = 1 and account_record.single_studio_id is not null then
    select source_key, display_name into only_location
    from public.eulerity_source_locations
    where account_id = p_account_id and is_active = true;
    select brand_id into target_brand_id from public.studios
    where id = account_record.single_studio_id and organization_id = account_record.organization_id and active = true;

    select id into mapping_id from public.studio_integrations
    where organization_id = account_record.organization_id
      and integration_type = 'eulerity'
      and studio_id = account_record.single_studio_id
      and is_active = true
    limit 1 for update;

    if mapping_id is null then
      insert into public.studio_integrations (
        organization_id, brand_id, studio_id, integration_type,
        integration_name, external_id, is_active, configuration
      ) values (
        account_record.organization_id, target_brand_id, account_record.single_studio_id,
        'eulerity', account_record.account_name,
        p_account_id::text || ':' || only_location.source_key, true,
        jsonb_build_object(
          'eulerity_account_id', p_account_id,
          'selector_key', only_location.source_key,
          'selector_label', only_location.display_name,
          'auto_mapped', true
        )
      );
    else
      update public.studio_integrations set
        integration_name = account_record.account_name,
        external_id = p_account_id::text || ':' || only_location.source_key,
        configuration = coalesce(configuration, '{}'::jsonb) || jsonb_build_object(
          'eulerity_account_id', p_account_id,
          'selector_key', only_location.source_key,
          'selector_label', only_location.display_name,
          'auto_mapped', true
        )
      where id = mapping_id;
    end if;
  end if;

  return location_count;
end;
$$;

create or replace function public.map_eulerity_location(
  p_organization_id bigint,
  p_account_id bigint,
  p_source_key text,
  p_studio_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  location_record public.eulerity_source_locations%rowtype;
  account_name text;
  target_brand_id bigint;
  mapping_id bigint;
begin
  select location, account.account_name into location_record, account_name
  from public.eulerity_source_locations location
  join public.eulerity_integration_accounts account on account.id = location.account_id
  where location.account_id = p_account_id and location.source_key = trim(p_source_key)
    and location.organization_id = p_organization_id and location.is_active = true
    and account.is_active = true;
  if location_record.id is null then raise exception 'Eulerity location not found'; end if;

  select brand_id into target_brand_id from public.studios
  where id = p_studio_id and organization_id = p_organization_id and active = true;
  if target_brand_id is null then raise exception 'Studio not found'; end if;

  select id into mapping_id from public.studio_integrations
  where organization_id = p_organization_id and integration_type = 'eulerity'
    and (studio_id = p_studio_id or external_id = p_account_id::text || ':' || trim(p_source_key))
    and is_active = true limit 1 for update;

  if mapping_id is null then
    insert into public.studio_integrations (
      organization_id, brand_id, studio_id, integration_type,
      integration_name, external_id, is_active, configuration
    ) values (
      p_organization_id, target_brand_id, p_studio_id, 'eulerity', account_name,
      p_account_id::text || ':' || trim(p_source_key), true,
      jsonb_build_object(
        'eulerity_account_id', p_account_id,
        'selector_key', trim(p_source_key),
        'selector_label', location_record.display_name,
        'auto_mapped', false
      )
    ) returning id into mapping_id;
  else
    update public.studio_integrations set
      brand_id = target_brand_id,
      studio_id = p_studio_id,
      integration_name = account_name,
      external_id = p_account_id::text || ':' || trim(p_source_key),
      configuration = coalesce(configuration, '{}'::jsonb) || jsonb_build_object(
        'eulerity_account_id', p_account_id,
        'selector_key', trim(p_source_key),
        'selector_label', location_record.display_name,
        'auto_mapped', false
      )
    where id = mapping_id;
  end if;
  return mapping_id;
end;
$$;

create or replace view public.eulerity_collection_accounts as
select organization_id, id as account_id, account_name, single_studio_id,
  last_discovered_at, last_validated_at
from public.eulerity_integration_accounts
where is_active = true;

create or replace view public.eulerity_collection_targets as
select
  account.organization_id,
  account.id as account_id,
  account.account_name,
  studio.brand_id,
  studio.id as studio_id,
  studio.studio_code,
  studio.studio_name,
  studio.timezone,
  mapping.id as integration_id,
  location.source_key as selector_key,
  location.display_name as selector_label
from public.eulerity_integration_accounts account
join public.studio_integrations mapping
  on mapping.organization_id = account.organization_id
 and mapping.integration_type = 'eulerity' and mapping.is_active = true
 and mapping.configuration ->> 'eulerity_account_id' = account.id::text
join public.eulerity_source_locations location
  on location.account_id = account.id and location.is_active = true
 and location.source_key = mapping.configuration ->> 'selector_key'
join public.studios studio
  on studio.id = mapping.studio_id and studio.organization_id = account.organization_id
 and studio.active = true
where account.is_active = true;

alter table public.eulerity_integration_accounts enable row level security;
alter table public.eulerity_source_locations enable row level security;
revoke all on table public.eulerity_integration_accounts, public.eulerity_source_locations,
  public.eulerity_collection_accounts, public.eulerity_collection_targets from public, anon, authenticated;
grant select, insert, update, delete on table public.eulerity_integration_accounts,
  public.eulerity_source_locations to service_role;
grant usage, select on sequence public.eulerity_integration_accounts_id_seq,
  public.eulerity_source_locations_id_seq to service_role;
grant select on table public.eulerity_collection_accounts, public.eulerity_collection_targets to service_role;

revoke all on function public.create_eulerity_account_with_secret(bigint, text, text, text, bigint),
  public.replace_eulerity_account_secret(bigint, bigint, text, text),
  public.get_eulerity_account_secret(bigint), public.sync_eulerity_locations(bigint, jsonb),
  public.map_eulerity_location(bigint, bigint, text, bigint)
  from public, anon, authenticated;
grant execute on function public.create_eulerity_account_with_secret(bigint, text, text, text, bigint),
  public.replace_eulerity_account_secret(bigint, bigint, text, text),
  public.get_eulerity_account_secret(bigint), public.sync_eulerity_locations(bigint, jsonb),
  public.map_eulerity_location(bigint, bigint, text, bigint)
  to service_role;

comment on table public.eulerity_integration_accounts is
  'Tenant-scoped Eulerity browser accounts. Login credentials are stored only in Supabase Vault.';
comment on table public.eulerity_source_locations is
  'Locations discovered from the Eulerity account selector. No credentials are stored here.';
comment on view public.eulerity_collection_targets is
  'Service-only configuration-driven Eulerity collection routing without secret values.';

commit;
