-- Privacy-safe Textellent class-alert configuration and delivery audit.
-- Customer contact information is intentionally absent from every object.

begin;

create table public.textellent_accounts (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  account_name text not null,
  sender_number text not null,
  secret_provider text not null default 'supabase_vault',
  secret_reference text not null,
  is_active boolean not null default true,
  last_validated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, account_name),
  constraint textellent_accounts_name_length check (char_length(trim(account_name)) between 2 and 120),
  constraint textellent_accounts_sender_e164 check (sender_number ~ '^\+[1-9][0-9]{7,14}$')
);

create table public.textellent_studio_assignments (
  organization_id bigint not null references public.organizations(id) on delete cascade,
  studio_id bigint primary key references public.studios(id) on delete cascade,
  textellent_account_id bigint not null references public.textellent_accounts(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.low_reservation_class_alert_settings (
  organization_id bigint not null references public.organizations(id) on delete cascade,
  studio_id bigint primary key references public.studios(id) on delete cascade,
  enabled boolean not null default false,
  maximum_reservations smallint not null default 2,
  lead_hours smallint not null default 6,
  earliest_send_time time not null default '08:00',
  message_template text not null default 'Hi! Your class at {studio} on {class_date} at {class_time} currently has low enrollment and may be cancelled. We will contact you if the class is cancelled.',
  excluded_class_types text[] not null default array['Private Party', 'Mobile Party', 'Marketing Event'],
  excluded_title_patterns text[] not null default array['DIY Pop in and Paint'],
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint low_reservation_threshold check (maximum_reservations between 1 and 20),
  constraint low_reservation_lead_hours check (lead_hours between 1 and 48),
  constraint low_reservation_message_length check (char_length(message_template) between 10 and 1000)
);

create table public.low_reservation_class_alert_deliveries (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  studio_id bigint not null references public.studios(id) on delete cascade,
  source_class_id text not null,
  class_starts_at timestamptz not null,
  scheduled_for timestamptz not null,
  reservation_count smallint not null,
  recipient_count smallint not null default 0,
  status text not null,
  textellent_message_ids text[] not null default '{}',
  error_code text,
  attempted_at timestamptz not null default now(),
  completed_at timestamptz,
  unique (studio_id, source_class_id),
  constraint low_reservation_delivery_status check (status in ('claimed', 'sent', 'skipped', 'failed')),
  constraint low_reservation_delivery_counts check (reservation_count >= 0 and recipient_count >= 0)
);

create index textellent_accounts_org_idx on public.textellent_accounts (organization_id, is_active);
create index textellent_assignments_account_idx on public.textellent_studio_assignments (textellent_account_id);
create index low_reservation_deliveries_due_idx on public.low_reservation_class_alert_deliveries (status, scheduled_for);

create extension if not exists supabase_vault with schema vault;

create or replace function public.create_textellent_account_with_secret(
  p_organization_id bigint,
  p_account_name text,
  p_sender_number text,
  p_auth_code text
)
returns bigint
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare
  account_id bigint;
  vault_secret_id uuid;
begin
  if char_length(trim(p_account_name)) not between 2 and 120 then raise exception 'Invalid account name'; end if;
  if p_sender_number !~ '^\+[1-9][0-9]{7,14}$' then raise exception 'Invalid sender number'; end if;
  if char_length(trim(p_auth_code)) not between 8 and 2048 then raise exception 'Invalid authentication code'; end if;

  insert into public.textellent_accounts (organization_id, account_name, sender_number, secret_reference)
  values (p_organization_id, trim(p_account_name), p_sender_number, 'pending:' || gen_random_uuid()::text)
  returning id into account_id;

  select vault.create_secret(
    jsonb_build_object('authCode', trim(p_auth_code))::text,
    'textellent-account-' || account_id::text,
    'Studio Intelligence Textellent API authentication code'
  ) into vault_secret_id;

  update public.textellent_accounts set secret_reference = vault_secret_id::text where id = account_id;
  return account_id;
end;
$$;

create or replace function public.get_textellent_account_secret(p_account_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare decrypted_value text;
begin
  select secret.decrypted_secret into decrypted_value
  from public.textellent_accounts account
  join vault.decrypted_secrets secret on secret.id = account.secret_reference::uuid
  where account.id = p_account_id and account.secret_provider = 'supabase_vault' and account.is_active = true;
  if decrypted_value is null then raise exception 'Textellent account secret not found'; end if;
  return decrypted_value::jsonb;
end;
$$;

create or replace function public.claim_low_reservation_class_alert(
  p_organization_id bigint,
  p_studio_id bigint,
  p_source_class_id text,
  p_class_starts_at timestamptz,
  p_scheduled_for timestamptz,
  p_reservation_count smallint
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare inserted_count integer;
begin
  insert into public.low_reservation_class_alert_deliveries (
    organization_id, studio_id, source_class_id, class_starts_at, scheduled_for,
    reservation_count, status
  ) values (
    p_organization_id, p_studio_id, p_source_class_id, p_class_starts_at,
    p_scheduled_for, p_reservation_count, 'claimed'
  ) on conflict (studio_id, source_class_id) do nothing;
  get diagnostics inserted_count = row_count;
  return inserted_count = 1;
end;
$$;

create or replace view public.low_reservation_class_alert_targets as
select
  setting.organization_id,
  setting.studio_id,
  studio.studio_code,
  studio.studio_name,
  studio.timezone,
  pts.external_id as pts_location_id,
  (pts.configuration ->> 'pts_account_id')::bigint as pts_account_id,
  assignment.textellent_account_id,
  textellent.sender_number,
  setting.enabled,
  setting.maximum_reservations,
  setting.lead_hours,
  setting.earliest_send_time,
  setting.message_template,
  setting.excluded_class_types,
  setting.excluded_title_patterns
from public.low_reservation_class_alert_settings setting
join public.studios studio on studio.id = setting.studio_id and studio.organization_id = setting.organization_id and studio.active
join public.studio_integrations pts on pts.studio_id = studio.id and pts.integration_type = 'pts' and pts.is_active
join public.textellent_studio_assignments assignment on assignment.studio_id = studio.id and assignment.organization_id = setting.organization_id
join public.textellent_accounts textellent on textellent.id = assignment.textellent_account_id and textellent.organization_id = setting.organization_id and textellent.is_active;

alter table public.textellent_accounts enable row level security;
alter table public.textellent_studio_assignments enable row level security;
alter table public.low_reservation_class_alert_settings enable row level security;
alter table public.low_reservation_class_alert_deliveries enable row level security;

revoke all on table public.textellent_accounts, public.textellent_studio_assignments,
  public.low_reservation_class_alert_settings, public.low_reservation_class_alert_deliveries,
  public.low_reservation_class_alert_targets from public, anon, authenticated;
grant select, insert, update, delete on table public.textellent_accounts, public.textellent_studio_assignments,
  public.low_reservation_class_alert_settings, public.low_reservation_class_alert_deliveries to service_role;
grant select on table public.low_reservation_class_alert_targets to service_role;
grant usage, select on sequence public.textellent_accounts_id_seq, public.low_reservation_class_alert_deliveries_id_seq to service_role;

revoke all on function public.create_textellent_account_with_secret(bigint, text, text, text),
  public.get_textellent_account_secret(bigint),
  public.claim_low_reservation_class_alert(bigint, bigint, text, timestamptz, timestamptz, smallint) from public, anon, authenticated;
grant execute on function public.create_textellent_account_with_secret(bigint, text, text, text),
  public.get_textellent_account_secret(bigint),
  public.claim_low_reservation_class_alert(bigint, bigint, text, timestamptz, timestamptz, smallint) to service_role;

comment on table public.low_reservation_class_alert_deliveries is
  'Privacy-safe class-alert audit. Customer names, emails, and phone numbers are prohibited.';
comment on view public.low_reservation_class_alert_targets is
  'Service-only class-alert routing configuration; secret values are resolved separately.';

commit;
