-- QuickBooks Online Phase 1: tenant-scoped, read-only connection foundation.
--
-- This migration creates no posting function and defaults every connection to
-- write-disabled. OAuth refresh credentials are stored only in Supabase Vault.
-- The source caches contain normalized fields, not raw API payloads.

begin;

create extension if not exists supabase_vault with schema vault;

create table public.quickbooks_connections (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  connection_name text not null,
  realm_id text not null,
  company_name text,
  country_code text,
  home_currency_code text,
  fiscal_year_start_month smallint,
  secret_provider text not null default 'supabase_vault',
  secret_reference text not null,
  granted_scopes text[] not null default array[]::text[],
  connection_status text not null default 'pending',
  write_enabled boolean not null default false,
  write_pause_reason text not null default 'Phase 1 read-only foundation',
  is_active boolean not null default true,
  token_expires_at timestamptz,
  last_discovered_at timestamptz,
  last_validated_at timestamptz,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, realm_id),
  unique (organization_id, connection_name),
  unique (organization_id, id),
  constraint quickbooks_connection_name_length
    check (char_length(trim(connection_name)) between 2 and 120),
  constraint quickbooks_realm_id_format check (realm_id ~ '^[0-9]{1,40}$'),
  constraint quickbooks_country_code_format
    check (country_code is null or country_code ~ '^[A-Z]{2}$'),
  constraint quickbooks_currency_code_format
    check (home_currency_code is null or home_currency_code ~ '^[A-Z]{3}$'),
  constraint quickbooks_fiscal_month
    check (fiscal_year_start_month is null or fiscal_year_start_month between 1 and 12),
  constraint quickbooks_secret_provider check (secret_provider = 'supabase_vault'),
  constraint quickbooks_connection_status
    check (connection_status in ('pending', 'connected', 'expiring', 'reconnect_required', 'error', 'disabled')),
  constraint quickbooks_phase1_read_only check (write_enabled = false),
  constraint quickbooks_write_pause_required
    check (write_enabled or nullif(trim(write_pause_reason), '') is not null)
);

create table public.quickbooks_studio_assignments (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  connection_id bigint not null,
  studio_id bigint not null references public.studios(id) on delete cascade,
  effective_from date not null default current_date,
  effective_to date,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (connection_id, studio_id, effective_from),
  foreign key (organization_id, connection_id)
    references public.quickbooks_connections(organization_id, id) on delete cascade,
  constraint quickbooks_assignment_date_range
    check (effective_to is null or effective_to >= effective_from)
);

create unique index quickbooks_one_active_connection_per_studio_idx
  on public.quickbooks_studio_assignments (studio_id)
  where is_active and effective_to is null;

create table public.accounting_email_connections (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  connection_name text not null,
  provider text not null default 'gmail',
  account_email text not null,
  secret_provider text not null default 'supabase_vault',
  secret_reference text not null,
  granted_scopes text[] not null default array[]::text[],
  connection_status text not null default 'pending',
  source_history_id text,
  is_active boolean not null default true,
  last_received_at timestamptz,
  last_validated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, provider, account_email),
  unique (organization_id, id),
  constraint accounting_email_connection_name_length
    check (char_length(trim(connection_name)) between 2 and 120),
  constraint accounting_email_provider check (provider = 'gmail'),
  constraint accounting_email_account_format
    check (account_email = lower(trim(account_email)) and account_email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
  constraint accounting_email_secret_provider check (secret_provider = 'supabase_vault'),
  constraint accounting_email_connection_status
    check (connection_status in ('pending', 'connected', 'reconnect_required', 'error', 'disabled'))
);

create table public.accounting_receipt_inboxes (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  connection_id bigint not null,
  email_connection_id bigint not null,
  email_address text not null,
  gmail_label_id text,
  routing_priority smallint not null default 100,
  is_active boolean not null default true,
  last_received_at timestamptz,
  last_validated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (email_connection_id, email_address),
  unique (organization_id, email_connection_id, id),
  foreign key (organization_id, connection_id)
    references public.quickbooks_connections(organization_id, id) on delete cascade,
  foreign key (organization_id, email_connection_id)
    references public.accounting_email_connections(organization_id, id) on delete cascade,
  constraint accounting_receipt_email_format
    check (email_address = lower(trim(email_address)) and email_address ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
  constraint accounting_receipt_routing_priority
    check (routing_priority between 1 and 1000)
);

create table public.accounting_email_messages (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  email_connection_id bigint not null,
  receipt_inbox_id bigint,
  source_message_id text not null,
  source_thread_id text,
  source_history_id text,
  internal_date timestamptz not null,
  sender_domain text,
  attachment_count integer not null default 0,
  routing_status text not null default 'collected',
  processed_at timestamptz,
  last_error_code text,
  retrieved_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (email_connection_id, source_message_id),
  foreign key (organization_id, email_connection_id)
    references public.accounting_email_connections(organization_id, id) on delete cascade,
  foreign key (organization_id, email_connection_id, receipt_inbox_id)
    references public.accounting_receipt_inboxes(organization_id, email_connection_id, id)
    on delete restrict,
  constraint accounting_email_message_id_length
    check (char_length(trim(source_message_id)) between 1 and 500),
  constraint accounting_email_attachment_count
    check (attachment_count >= 0),
  constraint accounting_email_routing_status
    check (routing_status in ('collected', 'routed', 'ambiguous', 'unmatched', 'processed', 'failed'))
);

create table public.quickbooks_accounts (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  connection_id bigint not null,
  source_account_id text not null,
  account_name text not null,
  fully_qualified_name text,
  account_number text,
  account_type text not null,
  account_subtype text,
  classification text,
  parent_source_account_id text,
  currency_code text,
  current_balance numeric(18,2),
  current_balance_with_subaccounts numeric(18,2),
  is_subaccount boolean not null default false,
  is_active boolean not null default true,
  sync_token text,
  source_created_at timestamptz,
  source_updated_at timestamptz,
  discovered_at timestamptz not null default now(),
  retrieved_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (connection_id, source_account_id),
  unique (organization_id, connection_id, source_account_id),
  foreign key (organization_id, connection_id)
    references public.quickbooks_connections(organization_id, id) on delete cascade,
  constraint quickbooks_source_account_id_length
    check (char_length(trim(source_account_id)) between 1 and 100),
  constraint quickbooks_account_name_length
    check (char_length(trim(account_name)) between 1 and 500),
  constraint quickbooks_account_currency_format
    check (currency_code is null or currency_code ~ '^[A-Z]{3}$')
);

create table public.quickbooks_account_reviews (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  connection_id bigint not null,
  source_account_id text not null,
  review_status text not null default 'pending',
  canonical_account_key text,
  recommended_account_name text,
  recommendation text,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (connection_id, source_account_id),
  foreign key (organization_id, connection_id, source_account_id)
    references public.quickbooks_accounts(organization_id, connection_id, source_account_id)
    on delete cascade,
  constraint quickbooks_account_review_status
    check (review_status in ('pending', 'aligned', 'rename_recommended', 'merge_recommended', 'inactive_recommended', 'mapping_required', 'accountant_review')),
  constraint quickbooks_account_review_actor
    check ((review_status = 'pending' and reviewed_at is null) or reviewed_at is not null)
);

create table public.quickbooks_vendors (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  connection_id bigint not null,
  source_vendor_id text not null,
  display_name text not null,
  company_name text,
  account_number text,
  normalized_name text not null,
  is_1099_vendor boolean,
  currency_code text,
  is_active boolean not null default true,
  sync_token text,
  source_created_at timestamptz,
  source_updated_at timestamptz,
  discovered_at timestamptz not null default now(),
  retrieved_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (connection_id, source_vendor_id),
  unique (organization_id, connection_id, source_vendor_id),
  foreign key (organization_id, connection_id)
    references public.quickbooks_connections(organization_id, id) on delete cascade,
  constraint quickbooks_source_vendor_id_length
    check (char_length(trim(source_vendor_id)) between 1 and 100),
  constraint quickbooks_vendor_display_name_length
    check (char_length(trim(display_name)) between 1 and 500),
  constraint quickbooks_vendor_normalized_name_length
    check (char_length(trim(normalized_name)) between 1 and 500),
  constraint quickbooks_vendor_currency_format
    check (currency_code is null or currency_code ~ '^[A-Z]{3}$')
);

create table public.quickbooks_transactions (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  connection_id bigint not null,
  source_transaction_id text not null,
  transaction_type text not null,
  transaction_date date,
  document_number text,
  counterparty_type text,
  counterparty_source_id text,
  counterparty_name text,
  bank_account_source_id text,
  accounts_payable_source_id text,
  total_amount numeric(18,2),
  currency_code text,
  exchange_rate numeric(20,10),
  source_status text not null default 'posted',
  source_private_note_present boolean not null default false,
  sync_token text,
  source_created_at timestamptz,
  source_updated_at timestamptz,
  source_hash text not null,
  retrieved_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (connection_id, transaction_type, source_transaction_id),
  unique (organization_id, connection_id, transaction_type, source_transaction_id),
  foreign key (organization_id, connection_id)
    references public.quickbooks_connections(organization_id, id) on delete cascade,
  constraint quickbooks_source_transaction_id_length
    check (char_length(trim(source_transaction_id)) between 1 and 100),
  constraint quickbooks_transaction_type_format
    check (transaction_type ~ '^[A-Za-z][A-Za-z0-9]{0,63}$'),
  constraint quickbooks_transaction_source_status
    check (source_status in ('posted', 'voided', 'deleted')),
  constraint quickbooks_transaction_currency_format
    check (currency_code is null or currency_code ~ '^[A-Z]{3}$'),
  constraint quickbooks_transaction_source_hash
    check (source_hash ~ '^[a-f0-9]{64}$')
);

create table public.quickbooks_transaction_lines (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  connection_id bigint not null,
  transaction_type text not null,
  source_transaction_id text not null,
  source_line_id text not null,
  line_number integer,
  detail_type text,
  description text,
  amount numeric(18,2),
  posting_type text,
  account_source_id text,
  class_source_id text,
  department_source_id text,
  customer_source_id text,
  vendor_source_id text,
  item_source_id text,
  tax_code_source_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (connection_id, transaction_type, source_transaction_id, source_line_id),
  foreign key (organization_id, connection_id, transaction_type, source_transaction_id)
    references public.quickbooks_transactions(organization_id, connection_id, transaction_type, source_transaction_id)
    on delete cascade,
  constraint quickbooks_transaction_line_id_length
    check (char_length(trim(source_line_id)) between 1 and 100),
  constraint quickbooks_transaction_line_number
    check (line_number is null or line_number >= 0),
  constraint quickbooks_transaction_line_posting_type
    check (posting_type is null or posting_type in ('Debit', 'Credit'))
);

create table public.quickbooks_sync_cursors (
  organization_id bigint not null references public.organizations(id) on delete cascade,
  connection_id bigint not null,
  entity_type text not null,
  cursor_value text,
  last_source_updated_at timestamptz,
  last_started_at timestamptz,
  last_completed_at timestamptz,
  last_status text not null default 'pending',
  last_row_count integer,
  last_error_code text,
  updated_at timestamptz not null default now(),
  primary key (connection_id, entity_type),
  foreign key (organization_id, connection_id)
    references public.quickbooks_connections(organization_id, id) on delete cascade,
  constraint quickbooks_sync_entity_type
    check (entity_type in ('company_info', 'accounts', 'vendors', 'transactions', 'attachments')),
  constraint quickbooks_sync_status
    check (last_status in ('pending', 'running', 'succeeded', 'failed', 'partial')),
  constraint quickbooks_sync_row_count
    check (last_row_count is null or last_row_count >= 0)
);

create index quickbooks_assignments_connection_idx
  on public.quickbooks_studio_assignments (connection_id, is_active, studio_id);
create index accounting_receipt_inboxes_routing_idx
  on public.accounting_receipt_inboxes (email_connection_id, is_active, routing_priority);
create index accounting_email_messages_processing_idx
  on public.accounting_email_messages (email_connection_id, routing_status, internal_date);
create index quickbooks_accounts_review_idx
  on public.quickbooks_accounts (organization_id, account_type, account_subtype, account_number);
create index quickbooks_vendors_normalized_idx
  on public.quickbooks_vendors (organization_id, normalized_name);
create index quickbooks_transactions_date_idx
  on public.quickbooks_transactions (connection_id, transaction_date, transaction_type);
create index quickbooks_transactions_updated_idx
  on public.quickbooks_transactions (connection_id, source_updated_at);
create index quickbooks_transaction_lines_account_idx
  on public.quickbooks_transaction_lines (connection_id, account_source_id);

create or replace function public.validate_quickbooks_studio_assignment()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if not exists (
    select 1 from public.studios studio
    where studio.id = new.studio_id
      and studio.organization_id = new.organization_id
  ) then
    raise exception 'QuickBooks studio assignment crosses organization boundary';
  end if;
  return new;
end;
$$;

create trigger validate_quickbooks_studio_assignment_trigger
before insert or update on public.quickbooks_studio_assignments
for each row execute function public.validate_quickbooks_studio_assignment();

create or replace function public.create_quickbooks_oauth_connection_with_secret(
  p_organization_id bigint,
  p_connection_name text,
  p_realm_id text,
  p_oauth_credentials jsonb,
  p_granted_scopes text[] default array[]::text[]
) returns bigint
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare
  connection_id bigint;
  existing_secret_reference text;
  vault_secret_id uuid;
begin
  if char_length(trim(p_connection_name)) not between 2 and 120 then
    raise exception 'Invalid QuickBooks connection name';
  end if;
  if trim(p_realm_id) !~ '^[0-9]{1,40}$' then
    raise exception 'Invalid QuickBooks realm ID';
  end if;
  if jsonb_typeof(p_oauth_credentials) <> 'object'
    or nullif(p_oauth_credentials ->> 'refresh_token', '') is null
  then
    raise exception 'Invalid QuickBooks OAuth credentials';
  end if;
  if not exists (select 1 from public.organizations where id = p_organization_id) then
    raise exception 'Organization not found';
  end if;

  select id, secret_reference
    into connection_id, existing_secret_reference
  from public.quickbooks_connections
  where organization_id = p_organization_id
    and realm_id = trim(p_realm_id)
  for update;

  if connection_id is null then
    insert into public.quickbooks_connections (
      organization_id, connection_name, realm_id, secret_reference,
      granted_scopes, connection_status, write_enabled, write_pause_reason
    ) values (
      p_organization_id, trim(p_connection_name), trim(p_realm_id),
      'pending:' || gen_random_uuid()::text, coalesce(p_granted_scopes, array[]::text[]),
      'connected', false, 'Phase 1 read-only foundation'
    ) returning id into connection_id;

    select vault.create_secret(
      p_oauth_credentials::text,
      'quickbooks-oauth-connection-' || connection_id::text,
      'Studio Intelligence QuickBooks Online OAuth refresh credential'
    ) into vault_secret_id;
  else
    if existing_secret_reference !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
      raise exception 'QuickBooks Vault secret reference is invalid';
    end if;
    vault_secret_id := existing_secret_reference::uuid;
    perform vault.update_secret(
      vault_secret_id,
      p_oauth_credentials::text,
      'quickbooks-oauth-connection-' || connection_id::text,
      'Studio Intelligence QuickBooks Online OAuth refresh credential'
    );
  end if;

  update public.quickbooks_connections
  set connection_name = trim(p_connection_name),
      secret_reference = vault_secret_id::text,
      granted_scopes = coalesce(p_granted_scopes, array[]::text[]),
      connection_status = 'connected',
      write_enabled = false,
      write_pause_reason = 'Phase 1 read-only foundation',
      is_active = true,
      last_validated_at = now(),
      updated_at = now()
  where id = connection_id;

  return connection_id;
end;
$$;

create or replace function public.get_quickbooks_connection_secret(p_connection_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare
  decrypted_value text;
begin
  select secret.decrypted_secret into decrypted_value
  from public.quickbooks_connections connection
  join vault.decrypted_secrets secret
    on secret.id = case
      when connection.secret_provider = 'supabase_vault'
       and connection.secret_reference ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        then connection.secret_reference::uuid
      else null
    end
  where connection.id = p_connection_id
    and connection.is_active = true
    and connection.connection_status <> 'disabled';

  if decrypted_value is null then
    raise exception 'QuickBooks connection secret not found';
  end if;
  return decrypted_value::jsonb;
end;
$$;

create or replace function public.create_accounting_gmail_connection_with_secret(
  p_organization_id bigint,
  p_connection_name text,
  p_account_email text,
  p_oauth_credentials jsonb,
  p_granted_scopes text[] default array[]::text[]
) returns bigint
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare
  connection_id bigint;
  existing_secret_reference text;
  vault_secret_id uuid;
begin
  if char_length(trim(p_connection_name)) not between 2 and 120 then
    raise exception 'Invalid Gmail connection name';
  end if;
  if lower(trim(p_account_email)) !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception 'Invalid Gmail account email';
  end if;
  if jsonb_typeof(p_oauth_credentials) <> 'object'
    or nullif(p_oauth_credentials ->> 'refresh_token', '') is null
  then
    raise exception 'Invalid Gmail OAuth credentials';
  end if;
  if not exists (select 1 from public.organizations where id = p_organization_id) then
    raise exception 'Organization not found';
  end if;

  select id, secret_reference
    into connection_id, existing_secret_reference
  from public.accounting_email_connections
  where organization_id = p_organization_id
    and provider = 'gmail'
    and account_email = lower(trim(p_account_email))
  for update;

  if connection_id is null then
    insert into public.accounting_email_connections (
      organization_id, connection_name, provider, account_email,
      secret_reference, granted_scopes, connection_status
    ) values (
      p_organization_id, trim(p_connection_name), 'gmail', lower(trim(p_account_email)),
      'pending:' || gen_random_uuid()::text, coalesce(p_granted_scopes, array[]::text[]),
      'connected'
    ) returning id into connection_id;

    select vault.create_secret(
      p_oauth_credentials::text,
      'accounting-gmail-connection-' || connection_id::text,
      'Studio Intelligence accounting receipt Gmail OAuth refresh credential'
    ) into vault_secret_id;
  else
    if existing_secret_reference !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
      raise exception 'Accounting Gmail Vault secret reference is invalid';
    end if;
    vault_secret_id := existing_secret_reference::uuid;
    perform vault.update_secret(
      vault_secret_id,
      p_oauth_credentials::text,
      'accounting-gmail-connection-' || connection_id::text,
      'Studio Intelligence accounting receipt Gmail OAuth refresh credential'
    );
  end if;

  update public.accounting_email_connections
  set connection_name = trim(p_connection_name),
      secret_reference = vault_secret_id::text,
      granted_scopes = coalesce(p_granted_scopes, array[]::text[]),
      connection_status = 'connected',
      is_active = true,
      last_validated_at = now(),
      updated_at = now()
  where id = connection_id;

  return connection_id;
end;
$$;

create or replace function public.get_accounting_email_connection_secret(p_connection_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, vault, pg_temp
as $$
declare
  decrypted_value text;
begin
  select secret.decrypted_secret into decrypted_value
  from public.accounting_email_connections connection
  join vault.decrypted_secrets secret
    on secret.id = case
      when connection.secret_provider = 'supabase_vault'
       and connection.secret_reference ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        then connection.secret_reference::uuid
      else null
    end
  where connection.id = p_connection_id
    and connection.is_active = true
    and connection.connection_status <> 'disabled';

  if decrypted_value is null then
    raise exception 'Accounting Gmail connection secret not found';
  end if;
  return decrypted_value::jsonb;
end;
$$;

create or replace function public.assign_quickbooks_connection_to_studio(
  p_organization_id bigint,
  p_connection_id bigint,
  p_studio_id bigint,
  p_effective_from date default current_date
) returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  assignment_id bigint;
begin
  if not exists (
    select 1 from public.quickbooks_connections connection
    where connection.id = p_connection_id
      and connection.organization_id = p_organization_id
      and connection.is_active = true
  ) then
    raise exception 'QuickBooks connection not found';
  end if;
  if not exists (
    select 1 from public.studios studio
    where studio.id = p_studio_id
      and studio.organization_id = p_organization_id
      and studio.active = true
  ) then
    raise exception 'Studio not found';
  end if;

  update public.quickbooks_studio_assignments
  set is_active = false,
      effective_to = greatest(p_effective_from - 1, effective_from),
      updated_at = now()
  where studio_id = p_studio_id
    and is_active = true
    and effective_to is null;

  insert into public.quickbooks_studio_assignments (
    organization_id, connection_id, studio_id, effective_from
  ) values (
    p_organization_id, p_connection_id, p_studio_id, p_effective_from
  )
  returning id into assignment_id;

  return assignment_id;
end;
$$;

create or replace view public.quickbooks_collection_targets as
select
  connection.organization_id,
  connection.id as connection_id,
  connection.connection_name,
  connection.realm_id,
  connection.company_name,
  connection.connection_status,
  connection.write_enabled,
  assignment.studio_id,
  studio.brand_id,
  studio.studio_code,
  studio.studio_name,
  studio.timezone,
  assignment.effective_from,
  assignment.effective_to
from public.quickbooks_connections connection
left join public.quickbooks_studio_assignments assignment
  on assignment.connection_id = connection.id
 and assignment.organization_id = connection.organization_id
 and assignment.is_active = true
 and assignment.effective_to is null
left join public.studios studio
  on studio.id = assignment.studio_id
 and studio.organization_id = connection.organization_id
 and studio.active = true
where connection.is_active = true;

create or replace view public.quickbooks_chart_of_accounts_review as
select
  account.organization_id,
  account.connection_id,
  connection.connection_name,
  connection.realm_id,
  connection.company_name,
  account.source_account_id,
  account.account_number,
  account.account_name,
  account.fully_qualified_name,
  account.account_type,
  account.account_subtype,
  account.classification,
  account.parent_source_account_id,
  account.is_subaccount,
  account.is_active,
  coalesce(review.review_status, 'pending') as review_status,
  review.canonical_account_key,
  review.recommended_account_name,
  review.recommendation,
  review.reviewed_by,
  review.reviewed_at,
  account.retrieved_at
from public.quickbooks_accounts account
join public.quickbooks_connections connection
  on connection.id = account.connection_id
 and connection.organization_id = account.organization_id
left join public.quickbooks_account_reviews review
  on review.connection_id = account.connection_id
 and review.source_account_id = account.source_account_id;

alter table public.quickbooks_connections enable row level security;
alter table public.quickbooks_studio_assignments enable row level security;
alter table public.accounting_email_connections enable row level security;
alter table public.accounting_receipt_inboxes enable row level security;
alter table public.accounting_email_messages enable row level security;
alter table public.quickbooks_accounts enable row level security;
alter table public.quickbooks_account_reviews enable row level security;
alter table public.quickbooks_vendors enable row level security;
alter table public.quickbooks_transactions enable row level security;
alter table public.quickbooks_transaction_lines enable row level security;
alter table public.quickbooks_sync_cursors enable row level security;

revoke all on table
  public.quickbooks_connections,
  public.quickbooks_studio_assignments,
  public.accounting_email_connections,
  public.accounting_receipt_inboxes,
  public.accounting_email_messages,
  public.quickbooks_accounts,
  public.quickbooks_account_reviews,
  public.quickbooks_vendors,
  public.quickbooks_transactions,
  public.quickbooks_transaction_lines,
  public.quickbooks_sync_cursors,
  public.quickbooks_collection_targets,
  public.quickbooks_chart_of_accounts_review
from public, anon, authenticated;

grant select, insert, update, delete on table
  public.quickbooks_connections,
  public.quickbooks_studio_assignments,
  public.accounting_email_connections,
  public.accounting_receipt_inboxes,
  public.accounting_email_messages,
  public.quickbooks_accounts,
  public.quickbooks_account_reviews,
  public.quickbooks_vendors,
  public.quickbooks_transactions,
  public.quickbooks_transaction_lines,
  public.quickbooks_sync_cursors
to service_role;

grant select on table
  public.quickbooks_collection_targets,
  public.quickbooks_chart_of_accounts_review
to service_role;

grant usage, select on sequence
  public.quickbooks_connections_id_seq,
  public.quickbooks_studio_assignments_id_seq,
  public.accounting_email_connections_id_seq,
  public.accounting_receipt_inboxes_id_seq,
  public.accounting_email_messages_id_seq,
  public.quickbooks_accounts_id_seq,
  public.quickbooks_account_reviews_id_seq,
  public.quickbooks_vendors_id_seq,
  public.quickbooks_transactions_id_seq,
  public.quickbooks_transaction_lines_id_seq
to service_role;

revoke all on function public.validate_quickbooks_studio_assignment()
  from public, anon, authenticated;
revoke all on function public.create_quickbooks_oauth_connection_with_secret(bigint,text,text,jsonb,text[])
  from public, anon, authenticated;
revoke all on function public.get_quickbooks_connection_secret(bigint)
  from public, anon, authenticated;
revoke all on function public.create_accounting_gmail_connection_with_secret(bigint,text,text,jsonb,text[])
  from public, anon, authenticated;
revoke all on function public.get_accounting_email_connection_secret(bigint)
  from public, anon, authenticated;
revoke all on function public.assign_quickbooks_connection_to_studio(bigint,bigint,bigint,date)
  from public, anon, authenticated;

grant execute on function public.create_quickbooks_oauth_connection_with_secret(bigint,text,text,jsonb,text[])
  to service_role;
grant execute on function public.get_quickbooks_connection_secret(bigint)
  to service_role;
grant execute on function public.create_accounting_gmail_connection_with_secret(bigint,text,text,jsonb,text[])
  to service_role;
grant execute on function public.get_accounting_email_connection_secret(bigint)
  to service_role;
grant execute on function public.assign_quickbooks_connection_to_studio(bigint,bigint,bigint,date)
  to service_role;

comment on table public.quickbooks_connections is
  'Tenant-scoped QuickBooks Online realms with OAuth refresh credentials stored only in Supabase Vault. Phase 1 connections are forcibly write-disabled.';
comment on table public.quickbooks_studio_assignments is
  'Effective-dated studio-to-QuickBooks realm routing. Supports any future number of studios without hardcoded company mappings.';
comment on table public.accounting_email_connections is
  'Tenant-scoped Gmail connections for receipt collection. OAuth refresh credentials are stored only in Supabase Vault; one Gmail connection may route many receipt addresses.';
comment on table public.accounting_receipt_inboxes is
  'Recipient address or alias routing from a secured Gmail connection to exactly one QuickBooks company connection.';
comment on table public.accounting_email_messages is
  'Privacy-minimized Gmail collection ledger keyed by immutable message ID for duplicate prevention and routing audit.';
comment on table public.quickbooks_accounts is
  'Read-only normalized QuickBooks chart-of-accounts cache used for cross-company review and future governed mappings.';
comment on table public.quickbooks_account_reviews is
  'Accountant-governed review status and canonical comparison key for each QuickBooks account; source account values remain unchanged.';
comment on table public.quickbooks_transactions is
  'Read-only normalized posted QuickBooks accounting entities. The standard Accounting API does not provide the pending bank-feed For review queue through this contract.';
comment on view public.quickbooks_collection_targets is
  'Service-only QuickBooks connection and active studio routing without OAuth credentials.';
comment on view public.quickbooks_chart_of_accounts_review is
  'Service-only cross-company chart-of-accounts review directory with source values and governed review metadata.';

commit;
