begin;

create extension if not exists supabase_vault with schema vault;

create table public.ga4_integration_accounts (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  account_name text not null,
  secret_provider text not null default 'supabase_vault',
  secret_reference text not null,
  is_active boolean not null default true,
  last_discovered_at timestamptz,
  last_validated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, account_name),
  constraint ga4_account_name_length check (char_length(trim(account_name)) between 2 and 120),
  constraint ga4_secret_provider check (secret_provider = 'supabase_vault')
);

create table public.ga4_source_properties (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  account_id bigint not null references public.ga4_integration_accounts(id) on delete cascade,
  property_id text not null,
  display_name text not null,
  account_display_name text,
  is_active boolean not null default true,
  discovered_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (account_id, property_id),
  constraint ga4_property_id_numeric check (property_id ~ '^[0-9]{1,30}$'),
  constraint ga4_property_name_length check (char_length(trim(display_name)) between 1 and 500)
);

create or replace function public.create_ga4_account_with_secret(
  p_organization_id bigint,
  p_account_name text,
  p_service_account jsonb
) returns bigint language plpgsql security definer set search_path = public, vault, pg_temp as $$
declare account_id bigint; vault_secret_id uuid;
begin
  if char_length(trim(p_account_name)) not between 2 and 120 then raise exception 'Invalid GA4 account name'; end if;
  if jsonb_typeof(p_service_account) <> 'object'
    or p_service_account ->> 'type' <> 'service_account'
    or nullif(trim(p_service_account ->> 'client_email'), '') is null
    or nullif(p_service_account ->> 'private_key', '') is null
  then raise exception 'Invalid Google service account JSON'; end if;

  insert into public.ga4_integration_accounts (organization_id, account_name, secret_reference)
  values (p_organization_id, trim(p_account_name), 'pending:' || gen_random_uuid()::text)
  returning id into account_id;

  select vault.create_secret(p_service_account::text, 'ga4-account-' || account_id::text,
    'Studio Intelligence GA4 service account credentials') into vault_secret_id;
  update public.ga4_integration_accounts set secret_reference = vault_secret_id::text, updated_at = now()
  where id = account_id;
  return account_id;
end; $$;

create or replace function public.get_ga4_account_secret(p_account_id bigint)
returns jsonb language plpgsql security definer set search_path = public, vault, pg_temp as $$
declare decrypted_value text;
begin
  select secret.decrypted_secret into decrypted_value
  from public.ga4_integration_accounts account
  join vault.decrypted_secrets secret on secret.id = account.secret_reference::uuid
  where account.id = p_account_id and account.is_active = true
    and account.secret_provider = 'supabase_vault';
  if decrypted_value is null then raise exception 'GA4 account secret not found'; end if;
  return decrypted_value::jsonb;
end; $$;

create or replace function public.sync_ga4_properties(p_account_id bigint, p_properties jsonb)
returns integer language plpgsql security definer set search_path = public, pg_temp as $$
declare account_record public.ga4_integration_accounts%rowtype; property_count integer;
begin
  select * into account_record from public.ga4_integration_accounts
  where id = p_account_id and is_active = true for update;
  if account_record.id is null then raise exception 'GA4 account not found'; end if;
  if jsonb_typeof(p_properties) <> 'array' then raise exception 'GA4 properties must be an array'; end if;

  update public.ga4_source_properties set is_active = false, updated_at = now()
  where account_id = p_account_id;
  insert into public.ga4_source_properties (
    organization_id, account_id, property_id, display_name, account_display_name, is_active, discovered_at
  ) select account_record.organization_id, p_account_id, trim(value ->> 'propertyId'),
      trim(value ->> 'displayName'), nullif(trim(value ->> 'accountDisplayName'), ''), true, now()
    from jsonb_array_elements(p_properties) value
    where trim(value ->> 'propertyId') ~ '^[0-9]{1,30}$'
      and nullif(trim(value ->> 'displayName'), '') is not null
  on conflict (account_id, property_id) do update set
    display_name = excluded.display_name, account_display_name = excluded.account_display_name,
    is_active = true, discovered_at = now(), updated_at = now();

  update public.ga4_integration_accounts set last_discovered_at = now(), last_validated_at = now(), updated_at = now()
  where id = p_account_id;

  update public.studio_integrations mapping set configuration = coalesce(mapping.configuration, '{}'::jsonb)
    || jsonb_build_object('ga4_account_id', p_account_id, 'property_id', property.property_id,
      'property_name', property.display_name)
  from public.ga4_source_properties property
  where property.account_id = p_account_id and property.is_active = true
    and mapping.organization_id = account_record.organization_id and mapping.integration_type = 'ga4'
    and mapping.external_id = property.property_id and mapping.is_active = true;

  select count(*) into property_count from public.ga4_source_properties
  where account_id = p_account_id and is_active = true;
  return property_count;
end; $$;

create or replace function public.map_ga4_property(
  p_organization_id bigint, p_account_id bigint, p_property_id text, p_studio_id bigint
) returns bigint language plpgsql security definer set search_path = public, pg_temp as $$
declare property_record public.ga4_source_properties%rowtype; target_brand_id bigint; mapping_id bigint;
begin
  select * into property_record from public.ga4_source_properties
  where organization_id = p_organization_id and account_id = p_account_id
    and property_id = trim(p_property_id) and is_active = true;
  if property_record.id is null then raise exception 'GA4 property not found'; end if;
  select brand_id into target_brand_id from public.studios
  where id = p_studio_id and organization_id = p_organization_id and active = true;
  if target_brand_id is null then raise exception 'Studio not found'; end if;

  select id into mapping_id from public.studio_integrations
  where organization_id = p_organization_id and integration_type = 'ga4'
    and (studio_id = p_studio_id or external_id = property_record.property_id)
    and is_active = true limit 1 for update;
  if mapping_id is null then
    insert into public.studio_integrations (
      organization_id, brand_id, studio_id, integration_type, integration_name,
      external_id, is_active, configuration
    ) values (
      p_organization_id, target_brand_id, p_studio_id, 'ga4', property_record.display_name,
      property_record.property_id, true,
      jsonb_build_object('ga4_account_id', p_account_id, 'property_id', property_record.property_id,
        'property_name', property_record.display_name)
    ) returning id into mapping_id;
  else
    update public.studio_integrations set brand_id = target_brand_id, studio_id = p_studio_id,
      integration_name = property_record.display_name, external_id = property_record.property_id,
      configuration = coalesce(configuration, '{}'::jsonb) ||
        jsonb_build_object('ga4_account_id', p_account_id, 'property_id', property_record.property_id,
          'property_name', property_record.display_name)
    where id = mapping_id;
  end if;
  return mapping_id;
end; $$;

create view public.ga4_collection_accounts as
select id as account_id, organization_id, account_name, last_discovered_at, last_validated_at
from public.ga4_integration_accounts where is_active = true;

create view public.ga4_collection_targets as
select account.id as account_id, mapping.organization_id, mapping.brand_id, mapping.studio_id,
  studio.studio_code, studio.studio_name, studio.timezone, mapping.id as integration_id,
  mapping.external_id as property_id, property.display_name as property_name
from public.ga4_integration_accounts account
join public.studio_integrations mapping on mapping.organization_id = account.organization_id
  and mapping.integration_type = 'ga4' and mapping.is_active = true
  and (mapping.configuration ->> 'ga4_account_id')::bigint = account.id
join public.studios studio on studio.id = mapping.studio_id and studio.active = true
join public.ga4_source_properties property on property.account_id = account.id
  and property.property_id = mapping.external_id and property.is_active = true
where account.is_active = true;

alter table public.ga4_integration_accounts enable row level security;
alter table public.ga4_source_properties enable row level security;
revoke all on table public.ga4_integration_accounts, public.ga4_source_properties,
  public.ga4_collection_accounts, public.ga4_collection_targets from anon, authenticated;
grant select, insert, update, delete on table public.ga4_integration_accounts, public.ga4_source_properties to service_role;
grant select on table public.ga4_collection_accounts, public.ga4_collection_targets to service_role;
grant usage, select on sequence public.ga4_integration_accounts_id_seq, public.ga4_source_properties_id_seq to service_role;
revoke all on function public.create_ga4_account_with_secret(bigint,text,jsonb),
  public.get_ga4_account_secret(bigint), public.sync_ga4_properties(bigint,jsonb),
  public.map_ga4_property(bigint,bigint,text,bigint) from public, anon, authenticated;
grant execute on function public.create_ga4_account_with_secret(bigint,text,jsonb),
  public.get_ga4_account_secret(bigint), public.sync_ga4_properties(bigint,jsonb),
  public.map_ga4_property(bigint,bigint,text,bigint) to service_role;

comment on table public.ga4_integration_accounts is 'Tenant-scoped GA4 service accounts with credentials stored only in Supabase Vault.';
comment on view public.ga4_collection_targets is 'Service-only GA4 account, property, and studio routing without secret values.';

commit;
