begin;

create table if not exists public.pts_order_attributes (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  brand_id bigint not null references public.brands(id) on delete cascade,
  studio_id bigint not null references public.studios(id) on delete cascade,
  pts_location_id text not null,
  order_id text not null,
  confirmation text,
  order_date date not null,
  postal_code text,
  booked_sales numeric(14, 2) not null default 0,
  discount_amount numeric(14, 2) not null default 0,
  discount_used boolean not null default false,
  discount_details jsonb not null default '[]'::jsonb,
  retrieved_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (studio_id, order_id),
  check (postal_code is null or postal_code ~ '^[0-9]{5}$'),
  check (discount_amount >= 0),
  check (jsonb_typeof(discount_details) = 'array')
);

create index if not exists pts_order_attributes_studio_date_idx
  on public.pts_order_attributes (studio_id, order_date desc);
create index if not exists pts_order_attributes_postal_code_idx
  on public.pts_order_attributes (postal_code, order_date desc);

alter table public.pts_order_attributes enable row level security;
revoke all on table public.pts_order_attributes from anon, authenticated;
grant select, insert, update, delete on table public.pts_order_attributes to service_role;
grant usage, select on sequence public.pts_order_attributes_id_seq to service_role;

create or replace view public.pts_order_geography_daily
with (security_invoker = true)
as
select
  organization_id,
  brand_id,
  studio_id,
  order_date,
  postal_code,
  count(*) as order_count,
  sum(booked_sales) as booked_sales,
  avg(booked_sales) as average_order_value,
  count(*) filter (where discount_used) as discounted_order_count,
  sum(discount_amount) as discount_amount,
  max(retrieved_at) as retrieved_at
from public.pts_order_attributes
where postal_code is not null
group by organization_id, brand_id, studio_id, order_date, postal_code;

revoke all on table public.pts_order_geography_daily from anon, authenticated;
grant select on table public.pts_order_geography_daily to service_role;

create or replace function public.upsert_pts_order_attributes(
  p_studio_id bigint,
  p_orders jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  affected_count integer := 0;
begin
  if p_studio_id is null then raise exception 'Studio is required'; end if;
  if p_orders is null or jsonb_typeof(p_orders) <> 'array' then
    raise exception 'PTS orders must be a JSON array';
  end if;
  if exists (
    select 1 from jsonb_to_recordset(p_orders) as value(studio_id bigint)
    where value.studio_id <> p_studio_id
  ) then raise exception 'PTS orders must match the requested studio'; end if;

  insert into public.pts_order_attributes (
    organization_id, brand_id, studio_id, pts_location_id, order_id,
    confirmation, order_date, postal_code, booked_sales, discount_amount,
    discount_used, discount_details, retrieved_at, updated_at
  )
  select
    value.organization_id, value.brand_id, value.studio_id,
    value.pts_location_id, value.order_id, value.confirmation, value.order_date,
    value.postal_code, coalesce(value.booked_sales, 0),
    greatest(coalesce(value.discount_amount, 0), 0),
    coalesce(value.discount_used, false), coalesce(value.discount_details, '[]'::jsonb),
    value.retrieved_at, now()
  from jsonb_to_recordset(p_orders) as value(
    organization_id bigint, brand_id bigint, studio_id bigint,
    pts_location_id text, order_id text, confirmation text, order_date date,
    postal_code text, booked_sales numeric, discount_amount numeric,
    discount_used boolean, discount_details jsonb, retrieved_at timestamptz
  )
  on conflict (studio_id, order_id) do update set
    confirmation = excluded.confirmation,
    order_date = excluded.order_date,
    postal_code = excluded.postal_code,
    booked_sales = excluded.booked_sales,
    discount_amount = excluded.discount_amount,
    discount_used = excluded.discount_used,
    discount_details = excluded.discount_details,
    retrieved_at = excluded.retrieved_at,
    updated_at = now();
  get diagnostics affected_count = row_count;
  return affected_count;
end;
$$;

revoke all on function public.upsert_pts_order_attributes(bigint, jsonb)
  from public, anon, authenticated;
grant execute on function public.upsert_pts_order_attributes(bigint, jsonb)
  to service_role;

comment on table public.pts_order_attributes is
  'Privacy-minimized PTS order enrichment containing five-digit billing ZIP and item discount totals; names and street addresses are excluded.';
comment on view public.pts_order_geography_daily is
  'Order count, booked sales, average order value, and discount use by studio, date, and five-digit ZIP.';

commit;
