begin;

create table public.homebase_role_mappings (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  role_name text not null,
  labor_category text not null default 'unmapped',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, role_name),
  constraint homebase_role_name_length check (char_length(trim(role_name)) between 1 and 300),
  constraint homebase_labor_category check (labor_category in ('cogs','overhead','unmapped'))
);

create table public.homebase_labor_role_daily (
  organization_id bigint not null references public.organizations(id) on delete cascade,
  brand_id bigint not null references public.brands(id) on delete cascade,
  studio_id bigint not null references public.studios(id) on delete cascade,
  labor_date date not null,
  role_name text not null default '',
  scheduled_hours numeric(12,4) not null default 0,
  actual_hours numeric(12,4) not null default 0,
  scheduled_cost numeric(14,2) not null default 0,
  actual_cost numeric(14,2) not null default 0,
  retrieved_at timestamptz not null,
  updated_at timestamptz not null default now(),
  primary key (studio_id, labor_date, role_name)
);
create index homebase_labor_role_daily_org_date_idx on public.homebase_labor_role_daily (organization_id,labor_date);

insert into public.homebase_role_mappings (organization_id,role_name,labor_category)
select distinct organization_id, seed.role_name, seed.labor_category
from public.homebase_integration_accounts
cross join (values
  ('Stage Artist','cogs'),('Floor Artist','cogs'),('Floor Artist: 20+','cogs'),('Bartender','cogs'),
  ('Studio Coordinator','overhead'),('Studio Admin','overhead')
) seed(role_name,labor_category)
on conflict (organization_id,role_name) do nothing;

drop function if exists public.replace_homebase_labor_range(bigint,date,date,jsonb,jsonb);
create function public.replace_homebase_labor_range(
  p_account_id bigint,p_start_date date,p_end_date date,p_daily jsonb,p_shifts jsonb,p_roles jsonb default '[]'::jsonb
) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare target public.homebase_collection_targets%rowtype; daily_count integer; shift_count integer; role_count integer;
begin
  if p_start_date is null or p_end_date is null or p_start_date>p_end_date or p_end_date-p_start_date>62 then raise exception 'Invalid Homebase labor range'; end if;
  if jsonb_typeof(p_daily)<>'array' or jsonb_typeof(p_shifts)<>'array' or jsonb_typeof(p_roles)<>'array' then raise exception 'Homebase labor payloads must be arrays'; end if;
  select * into target from public.homebase_collection_targets where account_id=p_account_id;
  if target.account_id is null or target.location_uuid is null then raise exception 'Validated Homebase target not found'; end if;
  delete from public.homebase_labor_daily where studio_id=target.studio_id and labor_date between p_start_date and p_end_date;
  delete from public.homebase_shift_labor where studio_id=target.studio_id and labor_date between p_start_date and p_end_date;
  delete from public.homebase_labor_role_daily where studio_id=target.studio_id and labor_date between p_start_date and p_end_date;
  insert into public.homebase_labor_daily (organization_id,brand_id,studio_id,labor_date,scheduled_hours,actual_hours,scheduled_cost,actual_cost,regular_hours,overtime_hours,double_overtime_hours,retrieved_at,updated_at)
  select target.organization_id,target.brand_id,target.studio_id,r.labor_date,coalesce(r.scheduled_hours,0),coalesce(r.actual_hours,0),coalesce(r.scheduled_cost,0),coalesce(r.actual_cost,0),coalesce(r.regular_hours,0),coalesce(r.overtime_hours,0),coalesce(r.double_overtime_hours,0),coalesce(r.retrieved_at,now()),now()
  from jsonb_to_recordset(p_daily) r(labor_date date,scheduled_hours numeric,actual_hours numeric,scheduled_cost numeric,actual_cost numeric,regular_hours numeric,overtime_hours numeric,double_overtime_hours numeric,retrieved_at timestamptz) where r.labor_date between p_start_date and p_end_date;
  get diagnostics daily_count=row_count;
  insert into public.homebase_shift_labor (organization_id,brand_id,studio_id,source_shift_id,source_timecard_id,role,department,labor_date,scheduled_start,scheduled_end,clock_in,clock_out,scheduled_hours,actual_hours,scheduled_cost,actual_cost,retrieved_at,updated_at)
  select target.organization_id,target.brand_id,target.studio_id,r.source_shift_id,r.source_timecard_id,r.role,r.department,r.labor_date,r.scheduled_start,r.scheduled_end,r.clock_in,r.clock_out,coalesce(r.scheduled_hours,0),coalesce(r.actual_hours,0),coalesce(r.scheduled_cost,0),coalesce(r.actual_cost,0),coalesce(r.retrieved_at,now()),now()
  from jsonb_to_recordset(p_shifts) r(source_shift_id bigint,source_timecard_id bigint,role text,department text,labor_date date,scheduled_start timestamptz,scheduled_end timestamptz,clock_in timestamptz,clock_out timestamptz,scheduled_hours numeric,actual_hours numeric,scheduled_cost numeric,actual_cost numeric,retrieved_at timestamptz) where r.source_shift_id is not null and r.labor_date between p_start_date and p_end_date;
  get diagnostics shift_count=row_count;
  insert into public.homebase_labor_role_daily (organization_id,brand_id,studio_id,labor_date,role_name,scheduled_hours,actual_hours,scheduled_cost,actual_cost,retrieved_at,updated_at)
  select target.organization_id,target.brand_id,target.studio_id,r.labor_date,coalesce(trim(r.role),''),sum(coalesce(r.scheduled_hours,0)),sum(coalesce(r.actual_hours,0)),sum(coalesce(r.scheduled_cost,0)),sum(coalesce(r.actual_cost,0)),max(coalesce(r.retrieved_at,now())),now()
  from jsonb_to_recordset(p_roles) r(labor_date date,role text,scheduled_hours numeric,actual_hours numeric,scheduled_cost numeric,actual_cost numeric,retrieved_at timestamptz)
  where r.labor_date between p_start_date and p_end_date group by r.labor_date,coalesce(trim(r.role),'');
  get diagnostics role_count=row_count;
  update public.homebase_integration_accounts set last_collected_at=now(),updated_at=now() where id=p_account_id;
  return jsonb_build_object('dailyRows',daily_count,'shiftRows',shift_count,'roleRows',role_count);
end; $$;

create or replace view public.homebase_labor_role_reporting with (security_invoker=true) as
select labor.organization_id,labor.brand_id,labor.studio_id,studio.studio_name,labor.labor_date,labor.role_name,
  coalesce(mapping.labor_category,'unmapped') labor_category,labor.scheduled_hours,labor.actual_hours,labor.scheduled_cost,labor.actual_cost,
  operations.total_sales,
  case when operations.total_sales>0 then labor.actual_cost/operations.total_sales*100 end actual_labor_percent
from public.homebase_labor_role_daily labor
join public.studios studio on studio.id=labor.studio_id
left join public.homebase_role_mappings mapping on mapping.organization_id=labor.organization_id and lower(mapping.role_name)=lower(labor.role_name)
left join public.pts_operations_daily operations on operations.studio_id=labor.studio_id and operations.report_date=labor.labor_date;

alter table public.homebase_role_mappings enable row level security;
alter table public.homebase_labor_role_daily enable row level security;
revoke all on table public.homebase_role_mappings,public.homebase_labor_role_daily,public.homebase_labor_role_reporting from public,anon,authenticated;
grant select,insert,update,delete on table public.homebase_role_mappings,public.homebase_labor_role_daily to service_role;
grant select on table public.homebase_labor_role_reporting to service_role;
grant usage,select on sequence public.homebase_role_mappings_id_seq to service_role;
revoke all on function public.replace_homebase_labor_range(bigint,date,date,jsonb,jsonb,jsonb) from public,anon,authenticated;
grant execute on function public.replace_homebase_labor_range(bigint,date,date,jsonb,jsonb,jsonb) to service_role;
comment on table public.homebase_labor_role_daily is 'Privacy-minimized daily Homebase labor totals by role; contains no employee identity, wage rate, or timecard identifiers.';
commit;
